### PR TITLE
Add Gnomes new default terminal kgx

### PR DESCRIPTION
**Pull request by SuperSandro2000**
# Description
Please include a summary of the change and which issue is fixed (if available). 
Please also include relevant motivation and context.

Fixes #(issue)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
No, I just forgot to undraft it.

**Comment by mirkobrombin** [comment]
Nice!

**Comment by jtojnar** [comment]
This will not be chosen on distros that install xterm as a fallback, opened https://github.com/bottlesdevs/Bottles/pull/1665.

**Comment by eathtespagheti** [comment]
is this correctly working for you? on gnome 45 with kgx I get the following error if I try to run anything with terminal
image

similar to #1406

**Comment by eathtespagheti** [comment]
Apparently formatting the kgx command in the same way as gnome-terminal fixes the issue:

``` python
        elif self.terminal[0] in ['xfce4-terminal']:
            command = ' '.join(self.terminal) % "'sh -c %s'" % f'{command}'
        elif self.terminal[0] in ['kgx', 'kitty', 'foot', 'konsole', 'gnome-terminal']:
            command = ' '.join(self.terminal) % "sh -c %s" % f'{command}'
```

Should I open another issue and then another PR?

**Pull request merged**
