### PR TITLE
feat: async fetch of components, installers and dependencies

### PR DESCRIPTION
**Pull request by Kinsteen**
# Description
This is the splitting of PR #2400. This part is only the "backend" part, with only the async fetching. No UI has been updated, so for example preferences menu will be empty until the components are fetched AND the menu is closed and reopened.

## Benchmark
I used `trickle` to limit the bandwidth of Bottles. Example: `trickle -s -d 10 bottles`
Here, the startup time is from the instant that the command is typed, to the instant when the bottles show up. It also counts the time when the window is not showing up.

| Without download limit | Startup time | Updated resources time (after startup) |
|--------------------------|--------------|----------------------------------------|
| Without the PR           | ~2s           | 0s                                     |
| With the PR              | -1s           | 0s                                     |

| Download limit of 50KB/s | Startup time | Updated resources time (after startup) |
|--------------------------|--------------|----------------------------------------|
| Without the PR           | 3s           | 0s                                     |
| With the PR              | 1.5s           | 1s                                     |

| Download limit of 10KB/s | Startup time | Updated resources time (after startup) |
|--------------------------|--------------|----------------------------------------|
| Without the PR           | 14s           | 0s                                     |
| With the PR              | 5s           | 10s                                     |

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by mirkobrombin — APPROVED** [review]

**Comment by Kinsteen** [comment]
My gift for this Christmas, is an improvement for index fetching! Before, index fetching could take up to 4 seconds (with a good connection) because all of it was sequential. This last commit makes them all parallel, which speeds up a lot this fetching. Combined with the previous async fetch of components, we have some quite performant result

**Comment by mirkobrombin** [comment]
Is this ready for merge?

**Comment by Kinsteen** [comment]
I think it is, yes

**Comment by mirkobrombin** [comment]
Nice.

There are some conflicts because of a previous PR. Can you fix them?

**Comment by Kinsteen** [comment]
Done!

**Pull request merged**
