### PR TITLE
Add Kron4ek menu options for runners

### PR DESCRIPTION
**Pull request by keenanweaver**
# Description
This is to enable https://github.com/bottlesdevs/components/pull/167

It adds a menu option for the [Kron4ek Wine runners](https://github.com/Kron4ek/Wine-Builds).

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.

1. Build Flatpak with provided JSON (had to remove the <url> tags out of the appdata file for it to fully build)
2. Clone https://github.com/keenanweaver/components/tree/kron4ek somewhere
3. Launch with LOCAL_COMPONENTS=/path/to/clonedir flatpak run
4. Download runners, apply to bottles, etc.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Were there any prior discussion to this?

**Comment by keenanweaver** [comment]
Unsure! I'm just a guy trying to close issues. :)

Feel free to close if it is deemed out of scope.

**Comment by mirkobrombin** [comment]
Might be useful as we don’t offer a pure vanilla version of wine (our Vanilla runner still have the staging patchset). I think the name of the new category must be changed to help the user better understanding Its purpose.

**Comment by TheEvilSkeleton** [comment]
Honestly, I feel like other runners aren't well explained either. There's a bit of fragmentation with runners.

**Comment by mirkobrombin** [comment]
I'm not completely sure about this:
[build_pkgs_unstable.yml](https://github.com/bottlesdevs/Bottles/pull/2072/files#diff-00cdf1ce72f8acfa8dd3e16bd2659ae8c9a455b43176edb6a3f4c51bc0d3650e)

only advanced users should change runner, beginners must keep Soda which covers must cases

**Comment by mirkobrombin** [comment]
Since there are a lot of runners in that collection, I think it's better to keep those runners in the **Other** section to avoid a giant loop.

Thanks for your contribution, _ left a comment in the other MR too.

**Pull request closed without merging**
