### PR TITLE
fix: Properly set paths for launch options dialog

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description

Fixes https://github.com/bottlesdevs/Bottles/issues/2693

This also rewords the dialog.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Tested by @MrQuerter

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Hey @MrQuerter, can you download https://github.com/bottlesdevs/Bottles/suites/11069341174/artifacts/563062286, and install it using `flatpak install bottles.flatpak`? Be sure you backup everything first.

**Comment by MrQuerter** [comment]
Well, it seems like it's working, but I'm not sure it should be seeing that it shows the problematic path from one of my active issues:
lotest
Can't say anything for script since I don't have any, but I did test working directory with game that requires more than the .exe file and it works if you select the correct path since selecting one folder before throws an error in the game.

bottle.yml entry:
```
External_Programs:
    6ee22e08-e890-44e5-a05e-8c2a5b4c5bb8:
        arguments: ''
        dxvk: true
        dxvk_nvapi: false
        executable: notepad++.exe
        folder: /run/user/1000/doc/39b2b30b/Notepad++
        fsr: false
        icon: com.usebottles.bottles-program
        id: 6ee22e08-e890-44e5-a05e-8c2a5b4c5bb8
        name: notepaddpp
        path: C:\Program Files\Notepad++\notepad++.exe
        pulseaudio_latency: false
        removed: null
        script: /run/user/1000/doc/41712fdc/template.yml
        virtual_desktop: false
        vkd3d: true
 ```
 
Also, just seen the `/run/user/1000/doc/` path and it makes a full copy of every working directory? Hopefully just because it's a github artifact version since I can't imagine it making a full copy of something that weights more than 10GB and some programs/games make a save file in the directory with .exe

**Comment by TheEvilSkeleton** [comment]
> Also, just seen the `/run/user/1000/doc/` path and it makes a full copy of every working directory? Hopefully just because it's a github artifact version since I can't imagine it making a full copy of something that weights more than 10GB and some programs/games make a save file in the directory with .exe

Afaik, it only remaps, not copy, so it's not duplicating any files. In my experience, this works reliably, as I've successfully used it with games.

**Comment by MrQuerter** [comment]
It sure does. Tested it right now and doesn't seem to have any issues and doesn't take space.

**Comment by TheEvilSkeleton** [comment]
Do you think I can merge?

**Comment by MrQuerter** [comment]
In my opinion sure. At least it's working and I can't find any problems with it.

**Comment by TheEvilSkeleton** [comment]
Alright. Thanks for testing!

**Comment by MrQuerter** [comment]
Just following up to say that it was indeed because of Github version. It works as expected in normal v51 from Flathub
test

**Pull request merged**
