### PR TITLE
Library changes & Quit fix

### PR DESCRIPTION
**Pull request by RozeFound**
# Description
Fix window not remembering size on Ctrl+Q, apparently force quit() is not a close request
Deprecate Gtk.Picture.set_pixbuf before it starts to produce warnings https://github.com/GNOME/gtk/commit/4bede73f62fccdf15316664563a1c777237d69a9
Set full application name in "No cover" placeholder in Library View, I thing It'll be more descriptive

Not sure if it fixes any issues tho

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by RozeFound** [comment]
Whoops, I forgot to create new branch before making a PR...

**Comment by TheEvilSkeleton** [comment]
@RozeFound any reason for closing this?

(I'm really busy right now so I can't review ATM)

**Comment by RozeFound** [comment]
There was no feedback so I thought it's bad structured.
I will divide it in two (Library changes and fix for ctrl+q) or more PR's instead

**Comment by Kinsteen** [comment]
I think it's okay keeping it like this, it's pretty small

**Comment by RozeFound** [comment]
To be honest I don't know how to separate it without redoing changes... 
So I hope you're okay with this PR 😅

**Comment by TheEvilSkeleton** [comment]
> To be honest I don't know how to separate it without redoing changes... So I hope you're okay with this PR sweat_smile

You'll need to use [`git rebase`](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase), but it's tedious to work with and gets annoying for every change. I can squash the commit, which shouldn't be a big deal.

**Comment by RozeFound** [comment]
Thanks! I'm pretty bad with git so it'll be a pleasure from your side

**Comment by RozeFound** [comment]
And I haven't tested it yet, so it might just not work :sweat_smile:

**Comment by TheEvilSkeleton** [comment]
What a coincidence, I opened https://github.com/bottlesdevs/Bottles/issues/2921 because I noticed that some information/tools are redundant or outdated for our use case, so I went ahead to create a meta-issue :D

**Comment by mirkobrombin** [comment]
Tested and everything works as expected. Merging when the CI finish.

**Comment by koplo199** [comment]
This PR needs to be rebased to trigger the missing `SonarQube Code Analysis` checks. Could it eventually be merged after that?

**Pull request merged**
