### PR TITLE
frontend: Use symbolic logo

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
In my opinion, this looks better.

image

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] UI

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Locally

### CODE REVIEW

**Comment by jannuary** [comment]
I don't have a strong preference. Iirc, this was inspired by Software using its colorful icon during loading

**Comment by mirkobrombin** [comment]
> I don't have a strong preference. Iirc, this was inspired by Software using its colorful icon during loading
> 
> Of course, I'd prefer not having this screen in the first place :)

I quote this

**Comment by jannuary** [comment]
FWIW, The justification of Software having a colorful icon is [this.](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/976#note_1023821)

**Comment by TheEvilSkeleton** [comment]
Thanks. I prefer to not have this screen either. I'm just going to close this MR, to keep it consistent with Software.

**Pull request closed without merging**
