### PR TITLE
Use FileDialog for all file/path pickers

### PR DESCRIPTION
**Pull request by penguinpee**
- Use `FileDialog` throughout
- Handle whatever `GLib.Error` throws our way
- Handle it the same way regardless of dialog

### CODE REVIEW

**Comment by penguinpee** [comment]
`Gtk.FileChooserNative` causes a segfault in `GTK_IS_FILE_SYSTEM_MODEL` when launching the _Working Directory_ dialog (`__choose_cwd()`).

This aligns `__choose_cwd()` with `__choose_pre_script()` and `__choose_post_script()`.

**Review by TheEvilSkeleton — CHANGES_REQUESTED** [review]

**Comment by TheEvilSkeleton** [comment]
Is it okay for you run `pre-commit run --all-files` and squash these commits? If not, I can do it

**Comment by penguinpee** [comment]
I don't have `pre-commit` set up.

However, I could squash locally and (force) push to my PR branch, if that helps.

**Comment by TheEvilSkeleton** [comment]
Don't worry, I'll squash and run `pre-commit` against it ^^

**Review by TheEvilSkeleton — APPROVED** [review]
Thanks a lot for your contribution :)

**Pull request merged**
