### PR TITLE
Draft: Remaining string fixes

### PR DESCRIPTION
**Pull request by comradekingu**
# Description
For some reason it is now "Wine", but still "wineprefix" for the time being.
Will also sort out the other strings marked for edit in WL.

Edit: Better than it was, but I think more can be found this round.
Then if it is offered for translation it is easier to single out the last errors and start improving strings to make it more elegant.

Fixes #(issue)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Review by Martinligabue — CHANGES_REQUESTED** [review]
at line 25 (com.usebottles.....in) and line 973 (details.ui) why has been added a - (minus) character?

**Comment by Martinligabue** [comment]
Please ask if you need help correcting other things, I'd love to contribute

**Comment by comradekingu** [comment]
@Martinligabue Meant to ask about it, thinking it is: "Wine runners and Proton runners"?
Otherwise it should be "Wine, and Proton runners".

**Comment by Martinligabue** [comment]
in my opinion it is quite repetitive, the shortened version would be more fluent and equally readable

**Comment by adrian5** [comment]
Just ran Bottles for the first time and the welcome message has a non-native feel to it:

> ### What are Runners?
> 
> These are compatibility layers which allows Windows software to be installed and run on Linux systems.

I know repetition is (often justifiably) frowned upon, but here I find it clearer to write:

> Runners are compatibility layers which ...

And since they are plural, it should read:

> Runners are compatibility layers which *allow* Windows software to be installed and run on Linux systems.

or

> Runners are compatibility layers, allowing Windows software to be installed and run on Linux systems.

Maybe you can add those to the Draft. Thanks!

**Comment by adrian5** [comment]
Found another:

> While the files on this page have been verified may be under proprietary license.

**Comment by comradekingu** [comment]
@Martinligabue Because it isn't "Wine, and Proton runners", it is the short form of "Wine runners, and Proton runners". 973 is no longer in.

**Comment by mirkobrombin** [comment]
Should I assume this PR is abandoned?

**Comment by comradekingu** [comment]
@@mirkobrombin 
I deduct the PR implementing a CoC without argument isn't the dedicated channel.
It is only a vehicle to thieve the efforts of others to prop up something masquerading as answering to your deflection.
What you instead lean on and defer to is "the committee", in an organization that cares as little about people like me as yourself.
You don't speak on my behalf, and there is no "we" there.

**Comment by mirkobrombin** [comment]
What the?

**Comment by adrian5** [comment]
Wasn't this mergable in its current form, or did the files in question change in the meantime (merge conflict)?

**Comment by mirkobrombin** [comment]
There are conflicts

**Pull request closed without merging**
