### PR TITLE
Some random improvements

### PR DESCRIPTION
**Pull request by A6GibKm**
I have yet to test all of these changes.

Some commits as [Use GLib.compute_checksum instead of hashlib](https://github.com/bottlesdevs/Bottles/commit/aa5418b3f11aaedf742e93086797b8ba78837515), [file: Use g_format_size to get human readable size](https://github.com/bottlesdevs/Bottles/commit/82a2a86954a09315843a8421f4b28c8967691f5f) are not really needed but can make maintenance simpler.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Is this MR planned to be worked at some point?

**Comment by A6GibKm** [comment]
> Is this MR planned to be worked at some point?

Yes I rebased it and reviewed it.

**Comment by A6GibKm** [comment]
I also simplified it a bit.

**Comment by mirkobrombin** [comment]
Wasn't there also file writing with GLib?

**Comment by A6GibKm** [comment]
I removed it, I might open a separate MR with it.

**Review by mirkobrombin — COMMENTED** [review]
All edits looks correct. It shouldn't cause breakage.

**Comment by TheEvilSkeleton** [comment]
Looks like there are conflicting files. Theoretically, once everything is resolved, it should be good to merge right?

**Comment by mirkobrombin** [comment]
I was convinced I had already merged it actually

**Comment by TheEvilSkeleton** [comment]
@A6GibKm can you fix this once again? Really sorry for making you go through all this.

**Comment by A6GibKm** [comment]
I am on vacation, ill try to fix it this during next week!

**Comment by TheEvilSkeleton** [comment]
Enjoy! :)

**Comment by A6GibKm** [comment]
I rebased the MR, but I didn't have to update it really.

**Comment by mirkobrombin** [comment]
> I rebased the MR, but I didn't have to update it really.

Just github moment

**Review by mirkobrombin — APPROVED** [review]

**Comment by A6GibKm** [comment]
It happens, it is a bit more common in gitlab tho.

**Comment by mirkobrombin** [comment]
Sad

**Pull request merged**
