### PR TITLE
chore: Clean and update manifest + automation

### LINKED ISSUE #2963: chore: Update manifest dependencies
A lot of dependencies are outdated in the flatpak manifest [com.usebottles.bottles.yml](https://github.com/bottlesdevs/Bottles/blob/main/com.usebottles.bottles.yml). Updating them and regenerating [com.usebottles.bottles.pypi-deps.yaml](https://github.com/bottlesdevs/Bottles/blob/main/com.usebottles.bottles.pypi-deps.yaml) probably wouldn't hurt.

### LINKED ISSUE #3003: [Request]: Migrate to org.freedesktop.Platform.VulkanLayer.gamescope
### Describe the bug

Attempting to install gamescope with `runtime/com.valvesoftware.Steam.Utility.gamescope/x86_64/stable` gives this warning:

```
Info: runtime com.valvesoftware.Steam.Utility.gamescope branch stable is end-of-life, with reason:
   The gamescope Flatpak has been migrated to org.freedesktop.Platform.VulkanLayer.gamescope.
```

However, Bottles only works with the Steam version, and does not detect the new migrated gamescope flatpak.

### To Reproduce

1. Run bottles with only the  `org.freedesktop.Platform.VulkanLayer.gamescope` flatpak installed.
1. Unable to use this version of gamescope to run applications.

### Package

Flatpak from Flathub

### Distribution

Fedora 38

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.4.6-200.fc38.x86_64
Disk:
    Total: 8337190912
    Free: 8337031168
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 9.7GiB
Bottles_envs: null
```

### Troubleshooting Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by koplo199**
# Description

Clean the flatpak manifest from modules no longer necessary (which were left over from [previous migrations](https://github.com/bottlesdevs/Bottles/commit/0e6e32b1ee894850935055a0199855d60055e926)), and update remaining modules/dependencies.

Additionally, support for [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker) has been added. It is then used by Github Actions to update automatically those modules/dependencies in the future.

It will check for updates every day, but using the [require-important-update](https://github.com/flathub/flatpak-external-data-checker#selectively-submitting-prs) feature of `flatpak-external-data-checker`, it will only submit a PR if "important" modules have been updated. Important modules are those who have `is-important: true` defined in the manifest.

The modules flagged as important are currently:

1. Bottles [runtime](https://github.com/bottlesdevs/runtime/releases)
2. [GameMode](https://github.com/FeralInteractive/gamemode)
3. [LatencyFlex](https://github.com/ishitatsuyuki/LatencyFleX)
4. [vkbasalt-cli](https://gitlab.com/TheEvilSkeleton/vkbasalt-cli)

If any of those modules are outdated, it will submit a PR looking like [this](https://github.com/koplo199/Bottles/pull/8) updating any outdated module.

- Fixes #2963
- Fixes #3003
- Fixes https://github.com/bottlesdevs/Bottles/issues/2983
- Add support for new gamescope path (https://github.com/flathub/flathub/pull/4329)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Tested locally and with CI build.

### CODE REVIEW

**Comment by koplo199** [comment]
It is technically ready for review, I'm converting to draft because https://github.com/bottlesdevs/runtime/pull/6 changes the asset naming scheme and I will need to reflect that change [here](https://github.com/bottlesdevs/Bottles/blob/a4c667d5f48ea5a509ee25982b65551aa714e590/com.usebottles.bottles.yml#L289) once merged.

**Comment by orowith2os** [comment]
You can probably remove the `com.valvesoftware.Steam` extension point too, gamescope is the only thing we're pulling from it, it seems.

**Comment by koplo199** [comment]
There's still [com.valvesoftware.Steam.Utility.steamtinkerlaunch](https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch) using it, while non-Proton compatibility layers are unsupported at the moment, I guess it doesn't hurt to leave it as is for the time being. It will spare debugging time for permission issues, which are kind of annoying as I unfortunately learned from #2961.

**Comment by orowith2os** [comment]
Can you drop a PR to the Flathub package, and I can merge all the changes?

**Comment by koplo199** [comment]
@orowith2os Sure, I opened https://github.com/flathub/com.usebottles.bottles/pull/449 which mirrors changes made here, but just as this PR it is also marked as draft because it needs https://github.com/bottlesdevs/runtime/pull/6.

**Comment by orowith2os** [comment]
I can land all three once all of the appropriate workflows are working as appropriate. Not sure if it's relevant here, but Mypy is complaining, that should probably be fixed.

**Comment by orowith2os** [comment]
Sorry, I can't merge the runtime repository changes. I'll bug Mirko about it.

**Comment by orowith2os** [comment]
Hm, why the separate com.usebottles.bottles.src manifest? I also noticed that in the Flathub PR, the Bottles source is duplicated there and in the main manifest.

**Comment by koplo199** [comment]
> Hm, why the separate com.usebottles.bottles.src manifest? I also noticed that in the Flathub PR, the Bottles source is duplicated there and in the main manifest.

I tried to explain a bit in [this](https://github.com/flathub/com.usebottles.bottles/pull/450#issuecomment-1679519264) comment, but I did it in order to avoid out of sync manifest between this repository, and the flathub one.

For instance, manifests already have diverged as we speak: here, the runtime here is at version [0.6](https://github.com/bottlesdevs/Bottles/blob/d8e142dcb005ceceee9eceb2ccaa2396ca9779ad/com.usebottles.bottles.yml#L286-L289), and on flathub it uses the latest [0.6.2](https://github.com/flathub/com.usebottles.bottles/blob/2f880a2e4e75126dc134e62c4a94c884a35b9b8d/com.usebottles.bottles.yml#L277-L280) version. Imagine that for a module being responsible for a bug, it would be horrendous to debug as it effectively makes reproducing impossible. Keeping manifests in sync would circumvent these situations.

There is, and should be, only one difference between manifests here and manifests on flathub: the location of the Bottles source directory. That change now belong to a distinct file named `com.usebottles.bottles.src.yaml`, so that the other two manifests (`com.usebottles.bottles.pypi-deps.yaml `, and `com.usebottles.bottles.yml`) can be mirrored on the flathub repository _without_ any change required!

Let's say tomorrow Bottles version `52` is released: on flathub the CI will detect this new version (thanks to the `x-checker-data` metadata in [com.usebottles.bottles.src.yaml](https://github.com/flathub/com.usebottles.bottles/blob/9da59ea07e4c4a7437213a928d9556d827b969a7/com.usebottles.bottles.src.yaml), this is the only yml file it will check for), and will automatically pull `com.usebottles.bottles.yml` and `com.usebottles.bottles.pypi-deps.yaml` from this repository at the `52` tag, overwriting the old one. This is why it currently looks like the Bottles source is duplicated on the flathub PR, but it's not, it will be overwritten in the following release.

Hopefully the motivation of this change is clearer with these explanations, let me know if there still is something unclear.

**Comment by orowith2os** [comment]
Alright, everything LGTM.

**Pull request merged**
