### PR TITLE
fix: Create bottle crashing if no Nvidia GPU and NVAPI installs

### LINKED ISSUE #2594: [Bug]: Problem with creating and deleting bottle
### Describe the bug

After the update to 50.2 I wanted to create a new bottle and there was an error after DXVK-NVAPI step. I launched bottles from terminal to see what it was and during bottle creation it shows "error while running async job" (more in later part). Also, after first restart there was a bug report (which I'll post in additional context box). Weirdly the bottle shows up, but it's broken like for example "browse files..." button throws "Could not show link. OpenURI portal is not available" error window. I then deleted the bottle and first time it worked, but now it still shows up every time you launch Bottles. It is not present in the `.var/app/com.usebottles.bottles/data/bottles/bottles`, but when you click on it it makes a folder there with only .fvs folder and bottle.yml. Also while we're at it. When you delete all bottles it has only this shadow instead of the text that shows when you don't have any bottles during launch:
shado
I think I'll just reinstall Bottles unless you want me to provide any other info.

### To Reproduce

1. Create new bottle
2. Restart Bottles
3. See crash report
4. Enter your bottle
5. Click "browse files..."
6. Delete bottle
7. Restart Bottles

### Package

Flatpak from Flathub

### Distribution

Linux Mint 21.1

### Debugging Information

```shell
Official Package: true
Version: '50.2'
DE/WM: cinnamon
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.15.0-58-generic
Disk:
    Total: 8356999168
    Free: 8356851712
RAM:
    MemTotal: 15.6GiB
    MemAvailable: 13.0GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
00:52:52 (ERROR) Error while running async job: <bound method Manager.create_bottle of <bottles.backend.managers.manager.Manager object at 0x7f11b7e8dff0>>
	Exception: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
 
  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1295, in create_bottle
    self.install_dll_component(config, "nvapi", version=nvapi_name)
  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1485, in install_dll_component
    manager = NVAPIComponent(_version)
  File "/app/share/bottles/bottles/backend/dlls/dll.py", line 40, in __init__
    self.check()
  File "/app/share/bottles/bottles/backend/dlls/dll.py", line 50, in check
    _path = os.path.join(self.base_path, path)
  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
```

### Additional context

This is the report that shows after you restart Bottles. It also gives bunch of GTK-warnings (plus few more of them after you copy the text):
errors

```py
join() argument must be str, bytes, or os.PathLike object, not 'NoneType'  File "/app/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1295, in create_bottle
    self.install_dll_component(config, "nvapi", version=nvapi_name)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 1485, in install_dll_component
    manager = NVAPIComponent(_version)

  File "/app/share/bottles/bottles/backend/dlls/dll.py", line 40, in __init__
    self.check()

  File "/app/share/bottles/bottles/backend/dlls/dll.py", line 50, in check
    _path = os.path.join(self.base_path, path)

  File "/usr/lib/python3.10/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)

  File "/usr/lib/python3.10/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
```

### PR DESCRIPTION
**Pull request by Kinsteen**
# Description
For some reasons, sometimes NVAPI wants to be installed even though the user doesn't have an Nvidia GPU. This PR adds another check to see if a DLL exists before check/install/uninstall. Also, a check to see if the user has a Nvidia card when creating a Bottle was implemented. This does not fix all occurences of the behavior, like for example when importing an existing Bottle, but it's a start. 

Fixes #2594

For reviewers to test: when not using a Nvidia card, create a bottle. You should not have any indication of NVAPI being installed.

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [X] locally, while triggering manually the error with different means

### CODE REVIEW

**Comment by MrQuerter** [comment]
Should I able to run this fix with this github action? https://github.com/bottlesdevs/Bottles/actions/runs/3979230456
I installed it but it prevents Bottles from running and it gives this output when you run Bottles from terminal:
```
Traceback (most recent call last):
  File "/app/bin/bottles", line 40, in <module>
    from bottles.frontend import main
  File "/app/share/bottles/bottles/frontend/main.py", line 36, in <module>
    from bottles.backend.logger import Logger
  File "/app/share/bottles/bottles/backend/logger.py", line 24, in <module>
    from bottles.backend.managers.journal import JournalManager, JournalSeverity
  File "/app/share/bottles/bottles/backend/managers/journal.py", line 19, in <module>
    from bottles.backend.utils import yaml
  File "/app/share/bottles/bottles/backend/utils/yaml.py", line 3, in <module>
    from bottles.backend.models.config import BottleConfig
  File "/app/share/bottles/bottles/backend/models/config.py", line 12, in <module>
    from bottles.backend.logger import Logger
ImportError: cannot import name 'Logger' from partially initialized module 'bottles.backend.logger' (most likely due to a circular import) (/app/share/bottles/bottles/backend/logger.py)
```

**Comment by Kinsteen** [comment]
Ah I made an oopsie, I will fix it later, sorry. When it is fixed, you'll be able to use it

**Comment by MrQuerter** [comment]
Creating bottle, opening location and deleting it seems to work now. Here's terminal output:
```
16:21:32 (INFO) Bottles Started! 
16:21:34 (INFO) Performing Bottles checks… 
16:21:34 (INFO) Dxvks found:
	 - dxvk-2.0
 
16:21:34 (INFO) Vkd3ds found:
	 - vkd3d-proton-2.8
 
16:21:34 (INFO) Nvapis found:
	 - dxvk-nvapi-v0.6
	 - dxvk-nvapi-v0.5.4
 
16:21:34 (INFO) Latencyflexs found:
	 - latencyflex-v0.1.1
 
16:21:34 (INFO) Runners found:
	 - sys-wine-7.0.1
	 - caffe-7.20
 
16:21:34 (INFO) Catalog dependencies loaded 
16:21:34 (INFO) Catalog installers loaded 
16:21:34 (INFO) Catalog components loaded 
16:21:58 (INFO) Generating bottle configuration… 
16:21:58 (INFO) Unpacking template: 2756a980-34b5-447c-b4ee-0d6034420979 
16:22:00 (INFO) Template unpacked successfully! 
16:22:00 (INFO) Using Wine Runtime tool -- send_status(-i) 
wineserver: using server-side synchronization.
wine: configuration in L"/home/username49/.var/app/com.usebottles.bottles/data/bottles/bottles/nvapitesting" has been updated.
16:22:08 (INFO) Applying environment: [gaming]… 
16:22:09 (INFO) Installing VKD3D… 
/home/username49/.var/app/com.usebottles.bottles/data/bottles/vkd3d/vkd3d-proton-2.8/x86/d3d12.dll -> /home/username49/.var/app/com.usebottles.bottles/data/bottles/bottles/nvapitesting/drive_c/windows/syswow64/d3d12.dll
/home/username49/.var/app/com.usebottles.bottles/data/bottles/vkd3d/vkd3d-proton-2.8/x64/d3d12.dll -> /home/username49/.var/app/com.usebottles.bottles/data/bottles/bottles/nvapitesting/drive_c/windows/system32/d3d12.dll
16:22:09 (INFO) Importing bundle to nvapitesting registry 
16:22:09 (INFO) Using Wine Registry CLI -- import_bundle 
esync: up and running.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
Failed to create /home/username49/.var/app/com.usebottles.bottles/data/bottles/bottles/nvapitesting/cache/mesa_shader for shader cache (No such file or directory)---disabling.
Failed to create /home/username49/.var/app/com.usebottles.bottles/data/bottles/bottles/nvapitesting/cache/mesa_shader for shader cache (No such file or directory)---disabling.
16:22:11 (INFO) Import bundle result: '' 
16:22:11 (INFO) New bottle created: nvapitesting 
16:22:11 (INFO) Using Wine Runtime tool -- send_status(-u) 
esync: up and running.
wine: configuration in L"/home/username49/.var/app/com.usebottles.bottles/data/bottles/bottles/nvapitesting" has been updated.
16:22:15 (INFO) Caching template… 
16:22:15 (INFO) Caching new template for gaming… 
16:22:15 (INFO) Deleting template: 2756a980-34b5-447c-b4ee-0d6034420979 
16:22:15 (INFO) Template deleted successfully! 
16:22:15 (INFO) Creating new template: 983a9602-0b2c-45f6-a652-c4e322a98295 
16:22:15 (INFO) Copying files … 
16:22:16 (INFO) New template gaming created 
16:22:16 (INFO) Bottles found:
	 - nvapitesting
 
16:22:19 (INFO) Setting Key sync=esync for bottle nvapitesting… 
16:22:19 (INFO) There is no running wineserver. 
16:22:25 (INFO) Opening the file manager in the path … 
16:22:35 (INFO) Stopping bottle… 
16:22:35 (INFO) There is no running wineserver. 
16:22:35 (INFO) Removing applications installed with the bottle… 
16:22:35 (INFO) Removing library entries associated with this bottle… 
16:22:35 (INFO) Removing the bottle… 
16:22:35 (INFO) Deleted the bottle in: /home/username49/.var/app/com.usebottles.bottles/data/bottles/bottles/nvapitesting 
```

**Comment by Kinsteen** [comment]
Perfect, thanks for your testing!

**Comment by MrQuerter** [comment]
I probably stumbled upon another problem. Don't know if it's because of this version, but it's first time I've seen anything like that.

I had trouble running the game from custom path so I tested my known 2 cases being PK2 and Notepad++. They work, but they also don't appear in bottle.yml unless you rename them (one of my unanswered questions in Bottles github). I also found a game that doesn't install because it wants to install in Z: drive and when you add the installer to the programs list manually it has this path in bottle.yml `/run/user/1000/doc/70f7a9b3/BigSolitairesPortable_1.4_Rev_3_English.paf.exe`. 
The solitaire game is from this site: https://portableapps.com/apps/games/big_solitaires_portable

I can reinstall Bottles now if you want me to check it in normal 50.2 version, but then it's possible I won't have the current problem anymore and won't be able to test this version.

**Comment by Kinsteen** [comment]
It looks like another error, probably wrong flatpak permissions I would say. Please open a new issue!

**Pull request merged**
