### PR TITLE
Updates the Components section of the Bottle Preferences

### PR DESCRIPTION
**Pull request by orowith2os**
I was looking for a way to change the runner easily a while ago, and missed this option. This would make it more visible, and with a note, so that the user doesn't accidentally miss it.

### CODE REVIEW

**Comment by mirkobrombin** [comment]
The description looks good but the title may be confusing as this menu contains dxvk also which is not really related to the runner

**Comment by mirkobrombin** [comment]
Runner Components it's fine. I think this MR should cooperate with #1930

**Comment by TheEvilSkeleton** [comment]
Honestly, my main gripe with this section is that it's a dropdown. "Components" is pretty vague. I spent 5 minutes trying to change the runner and overlooked Components a couple of times. I think a separate `AdwPreferencesGroup` would make things much easier to find.

**Comment by mirkobrombin** [comment]
Like how it was before the Adw port

**Comment by TheEvilSkeleton** [comment]
Should I create a Components `AdwPreferenceGroup` and submit an MR?

**Comment by mirkobrombin** [comment]
I think we can experiment with the current proposal and see if users complains or still get confused. It’s ok improving the ux but some times it’s also convenient to let users learn how the software works.

**Review by TheEvilSkeleton — CHANGES_REQUESTED** [review]
Can you rebase this? I'm considering merging it.

**Comment by orowith2os** [comment]
I dunno how to rebase asdkmnajlsk;dkasd but hopefully this works

**Comment by TheEvilSkeleton** [comment]
It's expecting `;`: https://github.com/bottlesdevs/Bottles/actions/runs/3091273478/jobs/5001140849#step:5:129.

**Review by TheEvilSkeleton — CHANGES_REQUESTED** [review]
It's expecting `;`: https://github.com/bottlesdevs/Bottles/actions/runs/3091273478/jobs/5001140849#step:5:129.

**Comment by orowith2os** [comment]
bleh, got it. Should be good to go

**Pull request merged**
