### PR TITLE
Update json flatpak manifest

### PR DESCRIPTION
**Pull request by mphojele**
# Description
Update the json flatpak manifest to match the  yml one.
Fixes #(issue)

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [X] Build and install with `flatpak-builder --install --user --force-clean com.usebottes.bottles.dev.json`
- [X] Run with `flatpak run --branch=master com.usebottles.bottles`

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
Thanks!

**Comment by mphojele** [comment]
@TheEvilSkeleton That was quick! Thanks! Too quick actually :see_no_evil: the source type for orjson should be file and not archive

**Comment by TheEvilSkeleton** [comment]
Good catch. I'll commit in a bit.

**Comment by mirkobrombin** [comment]
Thanks. I suggest using a yaml->json convertitor for things like this

**Comment by TheEvilSkeleton** [comment]
Yup, that's what I just did. I committed https://github.com/bottlesdevs/Bottles/commit/3dabe110c7051fa3b1980d47a5013d0cbb24562f.

**Pull request merged**
