### PR TITLE
Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
# Description
I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/Bottles/) that can improve the general code quality here.
This PR fixes a few of the issues detected.

### Summary of changes
- Remove mixed tabs and spaces from some indents.
- Merge unnecessary nested `if`s.
- Fix dangerous default argument (mutable used as default arg).
- Refactor `if` expression to simplify.
- Remove unused imports.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your work, I will test your - changes as soon as possible.

**Review by mirkobrombin — APPROVED** [review]

**Comment by akshgpt7** [comment]
@mirkobrombin, Thanks for merging the PR :)
I'd just like to point out that the issues fixed here were detected by running [DeepSource](https://deepsource.io/) analysis on the repo. If you like, you can activate analysis for your repository to detect such code quality issues/bug-risks on the fly for every new change made before merging it. It significantly reduces code review time. You can also use the Autofix feature to fix them with one click.

Here's how you can quickly activate DeepSource to continuously analyze your repository:
- Sign up on [DeepSource here](https://deepsource.io/signup) and Activate analysis for this repo.
- Create `.deepsource.toml` configuration which you can use to configure your analysis settings (This PR already added that, but you can still edit it).
- Activate/Check analysis [here](https://deepsource.io/gh/bottlesdevs/Bottles).

If you have any doubts or questions, you can check out the [docs](https://deepsource.io/docs), or feel free to reach out :)

**Comment by mirkobrombin** [comment]
It seems to me that I have already activated a code analysis tool but I forget to look at it

**Comment by akshgpt7** [comment]
DeepSource gets integrated with GitHub itself, so it just runs as any other check on PRs.
So once it is activated for a repo, it'll prompt on GitHub itself rather than manually looking at it every time :)
Let me know if you have any doubts whatsoever!

**Comment by akshgpt7** [comment]
@mirkobrombin, Just making sure if you need any help in activating analysis?
I ask so because you merged the `.deepsource.toml` file, which will only work if analysis is activated for that repository (through the steps mentioned above).

**Comment by mirkobrombin** [comment]
> @mirkobrombin, Just making sure if you need any help in activating analysis?
> I ask so because you merged the `.deepsource.toml` file, which will only work if analysis is activated for that repository (through the steps mentioned above).

I just don't have time at the moment. I will do it as soon as possible.

**Pull request merged**
