### PR TITLE
Update Code Of Conduct using common standards

### PR DESCRIPTION
**Pull request by pietrodicaprio**
The Code Of Conduct called CONTACT.md was too generic and can't be considered a Code Of Conduct.

### CODE REVIEW

**Comment by mirkobrombin** [comment]
I might be missing something. Which point in the text is generating conflicts? 
Those are in general rules of conduct of each community.

```
* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
* Gracefully accepting constructive criticism
* Focusing on what is best for the community
* Showing empathy towards other community members
* Respecting privacy
```

plus some already know grants:

```
Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.
``` 

I don't want to hire something, mine is an honest question. I'm not getting the point.

**Comment by mirkobrombin** [comment]
I might be missing something. Which point in the text is generating conflicts? 
Those are in general rules of conduct of each community.

```
* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
* Gracefully accepting constructive criticism
* Focusing on what is best for the community
* Showing empathy towards other community members
* Respecting privacy
```

plus some already know grants:

```
Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.
``` 

I don't want to hire something, mine is an honest question. I'm not getting the point.

**Comment by comradekingu** [comment]
@mirkobrombin 
You missed this:
>we as contributors and maintainers pledge

Nobody was ever asked to accept this text. (?) Nevertheless, it was slapped onto already made contributions, twice.

>making participation in our project and our community a harassment-free experience

This is a re-definition of the legal concept of harassment. Moreover, it replaces intent with interpretation, which is a further departure from the legal systems we have.
So right off the bat we have false security created in who actually supports or have even read it, what legal concepts mean, and how they function.

A function of which is people thought to be anti-social enough to engage in anti-social behavior somehow are thwarted by a text-file, that is more likely to be read by people that are gullible and vulnerable.

>regardless of …

Here we have lots of groups invoked, some of which are immutable.
What does the concept of singling people into groups do in addition to "everyone"? It does the opposite of cognitive behavioral therapy, which is the strongest non-mechanical psychological tool found to date.
It also charges the reading of it with very deeply held beliefs, which are likely to tie to similarly deeply held emotion.

If we further ask ourselves why rules need to be plastered to the wall like some mental institution, of why it needs to feature these concepts (hopefully contrary to evidence of problems), it sure doesn't help the supposed case for furthering said concerns.

For example "The right and responsibility" is challenged by " are expected to".
What the former refers to is "unacceptable behavior", which is now removed altogether.
The landscape of some of the things in the "harassment-free" list, are mutually exclusive, and no inroads have been made on a tangible system. It just invites conflict for no good reason. Conflict where none was had, and none needed to be invoked.

Similarly "inappropriate, threatening, offensive, or harmful" does the same thing. This lends itself to some credibility it doesn't have, and short of the even fewer things that have merit it sure falls foul of "standard", and is deeply generic.

These text-documents were never needed in the first place, and they did nothing positive.

I am not going to waste time on all the issues, but this version is a huge variant edit of the original text.
This means contributors have to read not only the text for every project, but also keep reading it for every edit here.

It just drapes itself in an old version of what is a further endless bloat that is now many many versions out of date, and also doesn't say the same thing.

For example, it has "project maintainers" replaced by "community leaders", because it is purposefully and statedly "political" and "anti-meritocratic".
The namesake also follows in the tradition of the catholic church and the mafia. It isn't just rules, so why boil it down to the concept of unwritten rules, when people stop contributing and rightly turn around on sight of such authoritarian drivel?

So it has happily diverted from the intent of its creator, but yet faces all the drawbacks of the backlash and history of disasters and wasted time that has left in its wake.

If people just read rules and followed rules, you would be aware that GitHub has its own set of rules.

I am just interested in contributing to libre software because I support it.
It is not possible to put this text into a license, even in edited form, because it is non-libre.

At best anecdotally, that didn't stop its creator from making a non-libre license. The list goes on.

**Comment by mirkobrombin** [comment]
I agree with the fact that it has not been put to a vote and this is my fault and I immediately restore the previous one. Regarding the body of the text: I leave Peter to answer that he thought so, so that you can come to an agreement.

**Pull request merged**
