### PR TITLE
Fixed Steam apps scanning on non-Flatpak systems

### LINKED ISSUE #1274: [Bug]: Steam prefixes doesn't get imported
### Describe the bug

After activating the experimental feature and restarting bottles I get "Steam path doesn't exist, creating now. " on every startup, but nothing gets imported. 

If I ctrl+r 

> INFO [Refresh] request received. 
> Traceback (most recent call last):
>   File "/usr/share/bottles/bottles/main.py", line 281, in __refresh
>     self.win.manager.update_bottles()
>   File "/usr/share/bottles/bottles/backend/managers/manager.py", line 159, in update_bottles
>     self.check_bottles(silent)
>   File "/usr/share/bottles/bottles/backend/managers/manager.py", line 828, in check_bottles
>     SteamManager.update_bottles()
>   File "/usr/share/bottles/bottles/backend/managers/steam.py", line 203, in update_bottles
>     shutil.rmtree(Paths.steam)  # generate new configs at start
>   File "/usr/lib/python3.10/shutil.py", line 712, in rmtree
>     onerror(os.lstat, path, sys.exc_info())
>   File "/usr/lib/python3.10/shutil.py", line 710, in rmtree
>     orig_st = os.lstat(path)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/lod/.local/share/bottles/steam

`

### To Reproduce

Just activate "Steam Proton prefixes" in Experiments

### Package

AUR ("bottles" package)

### Distribution

Arch

### Health Check

Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/share/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.17.1-arch1-1
Distro:
    Name: Arch Linux
    Version: Unknown
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.35'
Bottles_envs: null

### Display Protocol

Wayland

### Display Backend used by Bottles

Wayland

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Thesola10**
# Description

Fixes #1274

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.

- Launched `bottles` on a direct-from-Git install, apps which couldn't be scanned before now show up on the bottles list.
- Please test on Flatpak, Steam imports appeared to work before my fix on there.

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your contribution. On my steam flatpak installation, the "Apps" key is missing, there is "apps" instead. Can you check in your?

**Comment by Thesola10** [comment]
Good to know, the opposite is true on non-flatpak Steam installs. Will need to add a boolean+exception

**Comment by mirkobrombin** [comment]
> Good to know, the opposite is true on non-flatpak Steam installs. Will need to add a boolean+exception

I got report by another user which has steam from AUR, with "apps" too. A simple bool check should do the trick:

```
apps = local_config.get("UserLocalConfigStore", {}) \
            .get("Software", {}) \
            .get("Valve", {}) \
            .get("Steam", {}) 
apps = apps.get("apps") if apps.get("apps") else apps.get("Apps")
```

**Comment by AA1999** [comment]
```"Software"
	{
		"Valve"
		{
			"Steam"
			{
				"apps"
				{```
I was asked by Mirko to provide it
I installed the one from Arch repos

**Comment by mirkobrombin** [comment]
Nice, thanks again for your contribution!

**Pull request merged**
