### PR TITLE
fix: Various bug fixes and cleanups

### LINKED ISSUE #947: [BUG] An apostrophe (aka single quote) in a program's path or name breaks stuff
**Describe the bug**
If a program's path contains an apostrophe/single quote in its path, then launching it breaks with:

```
(11:56:45) INFO Running an executable on the bottle… 
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/bin/sh: -c: line 2: syntax error: unexpected end of file
```

Removing the apostrophe restores functionality.

**To Reproduce**
1. Add a game which contains an apostrophe in its path or .exe name, like e.g. Baldur's Gate.
2. Try to launch it.
3. Fail and see error.

### LINKED ISSUE #2903: [Bug]: App won't be executed unless it's executed in a terminal
### Describe the bug

App won't be executed unless it's executed with the "Execute in terminal" option

### To Reproduce

1. Try to execute one .exe file
2. Nothing show up
3. Try again with "execute in terminal" enable
4. It works

### Package

Flatpak from Flathub

### Distribution

Fedora 38

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-530-41-03/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.2.15-300.fc38.x86_64
Disk:
    Total: 8334897152
    Free: 8334729216
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 8.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
22:25:35 (INFO) Launching an executable… 
22:25:35 (INFO) Using EasyAntiCheat runtime 
22:25:35 (INFO) Using BattlEye runtime 
/app/bin/vmtouch: invalid option -- 'a'
/app/bin/vmtouch: invalid option -- 'a'

vmtouch v1.3.1 - the Virtual Memory Toucher by Doug Hoyte
Portable file system cache diagnostics and control

Usage: vmtouch [OPTIONS] ... FILES OR DIRECTORIES ...

Options:
  -t touch pages into memory
  -e evict pages from memory
  -l lock pages in physical memory with mlock(2)
  -L lock pages in physical memory with mlockall(2)
  -d daemon mode
  -m <size> max file size to touch
  -p <range> use the specified portion instead of the entire file
  -f follow symbolic links
  -F don't crawl different filesystems
  -h also count hardlinked copies
  -i <pattern> ignores files and directories that match this pattern
  -I <pattern> only process files that match this pattern
  -b <list file> get files or directories from the list file
  -0 in batch mode (-b) separate paths with NUL byte instead of newline
  -w wait until all pages are locked (only useful together with -d)
  -P <pidfile> write a pidfile (only useful together with -l or -L)
  -o <type> output in machine friendly format.  'kv' for key=value pairs.
  -v verbose
  -q quiet
kill : utilisation :kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... ou kill -l [sigspec]
22:25:58 (INFO) Launching an executable… 
22:25:58 (INFO) Using EasyAntiCheat runtime 
22:25:58 (INFO) Using BattlEye runtime 
/bin/sh: -c: ligne 1: fin de fichier (EOF) prématurée lors de la recherche du « ' » correspondant
/bin/sh: -c: ligne 2: erreur de syntaxe : fin de fichier prématurée
/bin/sh: -c: ligne 1: fin de fichier (EOF) prématurée lors de la recherche du « ' » correspondant
/bin/sh: -c: ligne 2: erreur de syntaxe : fin de fichier prématurée
kill : utilisation :kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... ou kill -l [sigspec]
```

### Additional context

_No response_

### LINKED ISSUE #3081: [Bug]: When enabling "Preload Game Files" in a specific bottle's settings', executable fails to launch if path to it contains an apostrophe.
### Describe the bug

When enabling "Preload Game Files" in a specific bottle's settings', executable fails to launch if path to it contains `'`, for instance `/home/gaming/.var/app/com.usebottles.bottles/data/bottles/bottles/Baldur's-Gate-3`.

I could not reproduce this issue when the path to the executable did not contain `'`.

### To Reproduce

1. Create a Bottle with a name containing `'` or choose an executable to launch with `'` to it's path.
2. Enable "Preload Game Files" in a bottle which you wish to launch it from.
3. Launch the executable.
4. Nothing happens.

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd: &amp;id002
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.4.11-hardened1-1-hardened
Disk:
    Total: 67488403456
    Free: 67488247808
RAM:
    MemTotal: 125.7GiB
    MemAvailable: 119.3GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
18:36:08 (INFO) Launching an executable… 
18:36:08 (INFO) Using EasyAntiCheat runtime 
18:36:08 (INFO) Using BattlEye runtime 
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/bin/sh: -c: line 2: syntax error: unexpected end of file
/bin/sh: -c: line 1: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 2: syntax error: unexpected end of file
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```

### Additional context

It is not evident _why_ the failure happens. An error message popup containing a message would be useful as a normal user might not understand that one has to launch the Bottles flatpak from the terminal to see additional information.

There should either be a check to prevent the user from choosing such path or creating a bottle with such name, but in my opinion the problem is that the shell script handling the preload is buggy, on the long term it would be better to fix it as `'` is a valid character under UNIX.

It is also true that renaming the bottle does not rename the folder's name containing the bottle, which I have realized during experimenting to narrow the issue's source. Even if it is a technical effort, the folder should be renamed as when creating the bottle the bottle's name is used, but on subsequent changes the folder's name and the name displayed by Bottles will get out of sync, causing potential confusion.

### LINKED ISSUE #3149: [Bug]: Enabling NVAPI sets dxvk.conf, overriding individual program's dxvk.conf
### Describe the bug

If NVAPI is enabled, Bottles creates a dxvk.conf in the wine prefix's root. As a consequence of this, dxvk.conf files that reside in a program's directory is not being respected.

### To Reproduce

1. Enable NVAPI
2. Make a dxvk.conf in a game directory next to the exe, with obvious overrides like:
```
dxgi.syncInterval = 0
d3d9.presentInterval = 0
# these force-disable vsync in a D3D9-11 app
```
3. Start the program in question
4. Observe the application settings not being respected
5. Disable NVAPI
6. Remove the dxvk.conf from the root of the bottle/wineprefix
7. Start the same program as step 3
8. Observe the application settings now being respected

### Package

Flatpak from Flathub

### Distribution

Arch Linux

### Debugging Information

```shell
Official Package: true
Version: '51.9'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-535-113-01/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.5.8-273-tkg-linux-tkg-pds
Disk:
    Total: 8336732160
    Free: 8336564224
RAM:
    MemTotal: 15.5GiB
    MemAvailable: 7.4GiB
Bottles_envs: null
```

### Troubleshooting Logs

_No response_

### Additional context

The game(s) in question don't have vsync adjustment themselves, hence the need to force it off. This applies to any setting though, like anisotropy.

### PR DESCRIPTION
**Pull request by koplo199**
# Description

Various bug fixes and cleanups.

Non exhaustive list:

- Fixes #3081
- Fixes #947
- Fixes #2903
- Fixes #3149
- Fixes programs/global overrides logic (backend).
- Fixes programs/global overrides logic (frontend).
- Fixes programs `WINEDLLOVERRIDES` not applying.
- Fixes programs `%command%` parsing.
- Fixes programs not launching from terminal if `arguments` contain environment variables.
- Add a check to verify the `Environment Variables` feature does not overlap with the `DLL Overrides` feature.
- Add a check to verify the `DLL Overrides` feature does not overlap with overrides managed by Bottles (e.g. DXVK, VKD3D...)
- Some cleanups and refactoring where I could.

And probably more that I've forgotten...

bug_fixes_screenshot

 \
It already required **a lot** of work and, unless it's an absolute necessity, I'm not keen to do much more modifications.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested with local builds.

### CODE REVIEW

**Review by mirkobrombin — APPROVED** [review]
LGTM. Thanks for your big contribution!

**Comment by orowith2os** [comment]
I think the linter's code smell hints are reasonable here. Let's fix up some of those before merging.

**Comment by koplo199** [comment]
Done :ok_hand:

**Comment by IPlayZed** [comment]
@mirkobrombin which release version will this be available on Flathub? Cheers!

**Comment by mirkobrombin** [comment]
> @mirkobrombin which release version will this be available on Flathub? Cheers!

[51.10](https://github.com/bottlesdevs/Bottles/pull/3099)

**Pull request merged**
