### PR TITLE
fix: fix some appimage only bugs

### PR DESCRIPTION
**Pull request by cat-master21**
# Description

Fix's the appimage zsync not being uploaded to release and it fixes the release build by change mksquashfs name.

- [ ] fix cabextract
- [x] fix appimage generation on release builds

Related to https://github.com/bottlesdevs/Bottles/issues/1272.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by mirkobrombin** [comment]
I'll keep this PR opened for the other appimage related problems, lilke the cabextract one

**Comment by TheEvilSkeleton** [comment]
I converted to draft to make it very clear that it is not finished. Feel free to mark it as review once finished.

**Comment by cat-master21** [comment]
So I have been quite busy lately but here is a status report if anybody wants to pick it up. Wine doesn't work because it tries and manually find ld with a set path. This might be rpath do not know. I tried running the library patcher that appimage builder uses but still same issue.

**Comment by TheEvilSkeleton** [comment]
I'm going to close this MR, but I mentioned in the main AppImage thread at https://github.com/bottlesdevs/Bottles/issues/1272#issuecomment-1258904775. Thanks for helping though! :heart:

**Pull request closed without merging**
