### PR TITLE
Fix unstable relase system

### PR DESCRIPTION
**Pull request by tiziodcaio**
# Description
The relase system was saturated by the unstable builds, now they will be added down in the actions menu

Fixes #(issue)

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [X] Running manually the workflow in my fork.

NOTE: The artifacts are zipped and we cannot solve it...

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your contribution

**Comment by mirkobrombin** [comment]
I see that the flatpak build is missing, is it due to a limitation or something else?

**Comment by tiziodcaio** [comment]
Solved (I think)

**Comment by mirkobrombin** [comment]
> Solved (I think)

Nice! Thanks again for your contribution

**Pull request merged**
