### PR TITLE
Revert "feat: add donate button"

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
This reverts commit b90c9b882fde73a4f41b4a5f15cad6961e20a97d.

# Description
There's already a donate button in the about dialog, which is the appropriate and non-distracting place. It's best not to distract users with pretty colors and whatnot

### CODE REVIEW

**Comment by EmoonX** [comment]
What about swapping pinky (🩷) for whitey (🤍)?

**Comment by TheEvilSkeleton** [comment]
We already have a Donate button in the about dialog:
image

I don't think it's really necessary to have it there

**Comment by EmoonX** [comment]
Haven't donations become more urgent matters as of late, though?
[https://usebottles.com/posts/2024-12-02-future-of-bottles/](https://usebottles.com/posts/2024-12-02-future-of-bottles/)

So a dedicated icon works as a way to draw further attention to that.

**Comment by TheEvilSkeleton** [comment]
Having it in the primary menu should cover that case without being too distracting. As someone with a high probability of having ADHD, having those buttons displayed right there is pretty distracting. I think the primary menu approach would work better because it's less distracting while being still there

**Pull request closed without merging**
