### PR TITLE
Improve issue forms

### LINKED ISSUE #1202: [Request]: Improving issue forms
### Tell us the problem or your need

I noticed some elements are missing, For example, the Bug Report template doesn't mention if Bottles is running on the X11 or Wayland backend, but it only asks what display protocol the session is using.

I think asking both questions is really important, especially when some people might force to X11 and forget about it. Or, use AppImage which forces to X11. So, having a section that asks what display backend Bottles is using should be important too.

https://github.com/bottlesdevs/Bottles/blob/b45925b243c2770a6119046b1e7cb1f9725e1da5/AppImageBuilder.yml#L130

### Describe the solution you'd like

Adding a section to ask specifically what display backend Bottles is running on, and fixing some inconsistencies here and there.

### Other solutions?

_No response_

### Additional context and references

I've pushed some changes in my fork: https://github.com/TheEvilSkeleton/Bottles/issues/new/choose. If accepted, I can submit an MR.

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
This MR improves some areas in issue forms:
- Adds capitalization in the names for consistency
- Improves clarification
- Adds a new section for which display backend Bottles is running on

Fixes #1202

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- Can be seen in https://github.com/TheEvilSkeleton/Bottles/issues/new/choose.

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
@mirkobrombin any suggestion?

**Comment by mirkobrombin** [comment]
In the bug report, I was thinking about a field for the Health check (Bottles -> Menu -> Health check)

```yaml
Display:
    X.org: true
    X.org (port): :99.0
    Wayland: false
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
        amd: &amp;id001
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 5.16.9-200.fc35.x86_64
Distro:
    Name: GNOME
    Version: '"41 (Flatpak runtime)"'
Tools:
    cabextract: true
    p7zip: true
    patool: true
    glibc_min: '2.33'
Bottles_envs: null
```

**Comment by TheEvilSkeleton** [comment]
@mirkobrombin what do you think?

**Comment by mirkobrombin** [comment]
I think it’s fine

**Pull request merged**
