### PR TITLE
Minor improvements and fixes to library

### PR DESCRIPTION
**Pull request by RozeFound**
# Description

Fixed "no cover" text not being shown
Centered items in LibraryView, I think it's look better, but if you don't agree, I can revert this

Fixes https://github.com/bottlesdevs/Bottles/issues/2458

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

I dont know how to test it tbh...

### CODE REVIEW

**Comment by RozeFound** [comment]
Sorry for PR without opening an issue again...

Also I want to clarify why am I contributing to Bottles all of a sudden.
I currently working on my own GTK4/Adwaita application, and I look at Bottles code as an example a lot.
I don't use any of assets of course, and don't straight copy-paste any code, so I hope you're fine with that

**Comment by TheEvilSkeleton** [comment]
That's fine. To be fair, your MRs have been really useful so far and I really like them. Feel free to join our Discord server if you want some help with development :)

**Review by TheEvilSkeleton — CHANGES_REQUESTED** [review]
Hmm... I'm not really happy with how it looks. It's off-center in halign:

image

I'd prefer that the valign to be at the top (`GTK_ALIGN_START`)

**Comment by RozeFound** [comment]
Hmm, I'll look into it

**Comment by RozeFound** [comment]
How does it look now?

**Comment by TheEvilSkeleton** [comment]
Honestly, I really like how "No Thumbnail" looks, but we'll have to discuss its looks in https://github.com/bottlesdevs/Bottles/issues/2458

**Review by TheEvilSkeleton — CHANGES_REQUESTED** [review]
After some light testing, I discovered that the entries aren't rearranged after we remove or add an entry until we restart it:

[Screencast from 2023-03-24 17-23-15.webm](https://user-images.githubusercontent.com/50847364/227644274-dde85620-5835-4d64-b93f-2a0617d6c29c.webm)

**Comment by RozeFound** [comment]
> Honestly, I really like how "No Thumbnail" looks, but we'll have to discuss its looks in https://github.com/bottlesdevs/Bottles/issues/2458

Well, That was not me who added that, it was in code just disabled

**Comment by TheEvilSkeleton** [comment]
Oh, :sweat_smile:

**Review by TheEvilSkeleton — CHANGES_REQUESTED** [review]
Hmm... it looks like it gets "stuck" when you remove an entry, but centers when you restart the app:

[Screencast from 2023-03-24 21-51-06.webm](https://user-images.githubusercontent.com/50847364/227679641-780093f1-3ba3-4bdc-8ad3-cef1e004efda.webm)

Can you make it centered all the time?

**Comment by RozeFound** [comment]
That's weird...

**Comment by TheEvilSkeleton** [comment]
Yeah :/

**Comment by RozeFound** [comment]
oh. `self.update()` not called on entry removal, that's why

**Comment by RozeFound** [comment]
Sorry to make you test every little change... But this time I hope it'll work

**Comment by TheEvilSkeleton** [comment]
Don't worry about it. I do QA a lot, so I'm used to it :)

**Comment by TheEvilSkeleton** [comment]
I just tested it, and it looks good to me. I'll let it sit for a bit and wait until we figure out https://github.com/bottlesdevs/Bottles/issues/2458... unless it takes a really long time

**Review by mirkobrombin — APPROVED** [review]

**Comment by TheEvilSkeleton** [comment]
Looks like there won't be any response anytime soon. I'll just merge it. Thank you once again!

**Review by TheEvilSkeleton — APPROVED** [review]
Looks like there won't be any response anytime soon. I'll just merge it. Thank you once again!

**Comment by TheEvilSkeleton** [comment]
> I dont know how to test it tbh...

@RozeFound I just noticed this in the original comment. If you want to test next time, click on the Details button in the Build Flatpak field at the bottom of the MR:

image

You won't see this button in this MR, as I just merged it. You can open another MR and try it there. Afterwards, press "Summary", and then click "bottles-x86_64" under "Artifacts". It should download a zip archive. Then, unzip it, and then run `flatpak install bottles.flatpak`. I highly recommend backing up `~/.var/app/com.usebottles.bottles` before testing experimental builds.

**Pull request merged**
