### PR TITLE
frontend: Refactor Onboard

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
- Adds a tutorial that explains what Wine, runners and Bottles are, as well as explaining how to use Bottles
- Rewrites the UI to make it smoother

Closes https://github.com/bottlesdevs/Bottles/issues/2472

~~Blocked by https://github.com/bottlesdevs/Bottles/pull/2505, for notifications~~

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] UI/UX

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Locally

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
We should follow [Tour](https://gitlab.gnome.org/GNOME/gnome-tour)'s UI and UX:

https://user-images.githubusercontent.com/50847364/219226866-f07bf7d2-3381-44f6-925d-374ba3fcd78e.mp4

**Comment by TheEvilSkeleton** [comment]
[Screencast from 2023-03-02 21-34-59.webm](https://user-images.githubusercontent.com/50847364/222617145-6dec1895-2672-4db8-ae50-de2d4c192710.webm)

**Comment by jannuary** [comment]
Do we really need a "Skip" button?

**Comment by TheEvilSkeleton** [comment]
There are many pages, so I'd say that it would be desirable to have a skip button. If you think it's unnecessary, then I can remove it.

**Comment by jannuary** [comment]
It's jusy really obnoxious, and I haven't seen other apps with such pattern.

I wonder if we could decouple the tour from the initial setup?

**Comment by TheEvilSkeleton** [comment]
I tried to do it a few days ago and couldn't figure out. They implement their own widget, as far as I know.

**Comment by jannuary** [comment]
I meant to download components in a separate, invisible for the user step

Then the close button could be used as a "skip" button

**Comment by TheEvilSkeleton** [comment]
I'm not sure. The user could create a new bottle at the same time Bottles is setting itself up

**Comment by jannuary** [comment]
Well, they shouldn't be.

**Comment by TheEvilSkeleton** [comment]
...So we'll just prevent them from creating a bottle?

**Comment by jannuary** [comment]
I mean, that's what we do already, yes.

There could be a banner saying "Finishing setup..." or something along the lines and a loading bar with .osd styling to reassure the user that it's still loading.

Also, maybe we could have it install components in the background, so that one could go through the tour and not actually see any loading at all

**Comment by TheEvilSkeleton** [comment]
Alright. I don't want to use GtkInfoBar, as it's deprecated. I would rather wait for AdwBanner until it's stable, or bundle 1.3.rc for the time being. What do you think?

**Comment by jannuary** [comment]
Hmm. 44 drops pretty soon, right?

**Comment by TheEvilSkeleton** [comment]
In 20 days

**Comment by TheEvilSkeleton** [comment]
Even then, we still have to wait until 44 runtime drops, which will take longer

**Comment by kbdharun** [comment]
> Do we really need a "Skip" button?

Skip would be useful for existing users who reinstalled bottles in a new machine/existing one, as we don't need to go through the steps again. But if there is no difference in the speed, then I don't think it is necessary.

**Comment by TheEvilSkeleton** [comment]
libadwaita 1.3 was release! https://blogs.gnome.org/alexm/2023/03/17/libadwaita-1-3/

**Comment by TheEvilSkeleton** [comment]
Closing this as I won't be working on it anymore

**Pull request closed without merging**
