### PR TITLE
fix: local builds not being able to run 32bit programs

### PR DESCRIPTION
**Pull request by underlinejakez**
# Description
For some reason, when building locally, you can't run **_any_** 32-bit programs without `org.freedesktop.Platform.Compat.i386`. This solves, but its weird that it don't happen on the Flathub build.

```sh
jake@fedora:~$ flatpak run --env=LC_ALL=C --command=sh com.usebottles.bottles 
[📦 com.usebottles.bottles ~]$ wine --version
sh: /app/bin/wine: cannot execute: required file not found
[📦 com.usebottles.bottles ~]$ wine64 --version
wine-9.0
[📦 com.usebottles.bottles ~]$ /home/jake/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/bin/wine --version
sh: /home/jake/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/bin/wine: cannot execute: required file not found
[📦 com.usebottles.bottles ~]$ /home/jake/.var/app/com.usebottles.bottles/data/bottles/runners/soda-9.0-1/bin/wine64 --version
wine-experimental.bleeding.edge.9.0.93696.20240429 ( TkG Plain )
```
Which cause the error I shown:
```sh
/bin/sh: line 1: /app/bin/wine: cannot execute: required file not found
17:44:25 (INFO) Runners found:
	 - soda-9.0-1
	 - sys-
```

The problem almost gets away because of this line of code but trying to create a 32bit prefix or anything related to running 32bit quickly break and bottles interface doesn't show any sign of problem.
https://github.com/bottlesdevs/Bottles/blob/e93cd189e966ed0daf515f8398f12e2cb6dcf620/bottles/backend/wine/winecommand.py#L473-L474

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
I built and installed manually from master and after the modification using:
`flatpak run org.flatpak.Builder --user --install-deps-from=flathub --install --force-clean build-dir com.usebottles.bottles.yml`

_edited to explain better the issue ~~(i will try to rename the commit later)~~_

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your contribution. This is indeed weird, need to test it locally on my end

**Comment by underlinejakez** [comment]
Hi, I edited the PR and commit to reflect what really is going on (hope I didn't messed up with git). I'll be happy if you could take a look again.

**Review by mirkobrombin — APPROVED** [review]
LGTM. Let me know if you have other commits before I merge

**Comment by underlinejakez** [comment]
I think this is all.

**Comment by underlinejakez** [comment]
Superseded by #3581.

**Pull request closed without merging**
