### PR TITLE
Add drag'n'drop to execute programs

### LINKED ISSUE #166: [Request] Ability to drag'n'drop exe to bottle to start it
**Is your feature request related to a problem? Please describe.**
Would be nice to have ability to drag and drop exe to bottle to start it.

**Describe the solution you'd like**
Having ability to drag and drop exe to interface.

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by axtloss**
# Description
This allows users to drag executables into the bottles window to execute them

Fixes #166 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [ ] Test A
- [ ] Test B

Currently this only allows for basic drag'n'drop when in the bottles details window, but I'll expand it to show an overlay when dragging a file into the window and possibly also allow dragging files into the bottles entry on the bottles list to execute stuff using a bottle.

### CODE REVIEW

**Comment by vchernin** [comment]
Unfortunately this will probably be impacted by https://gitlab.gnome.org/GNOME/gtk/-/issues/4719

**Comment by axtloss** [comment]
> Unfortunately this will probably be impacted by https://gitlab.gnome.org/GNOME/gtk/-/issues/4719

Just tested it, yeah it does. Only paths that bottles has access to work properly.

I guess we could just wait until this gets fixed and then merge it?

**Comment by mirkobrombin** [comment]
Aren't our users already aware of the sandbox? I think we can safely implement this and wait for the fix.

**Comment by vchernin** [comment]
Since still only GTK4/nautilus at least tries to have support for the file transfer portal, this likely won't be a dependable feature for some time across most distros/environments. 

So I guess just implement and hope it's not confusing for users when it doesn't work due to that bug/are using a unsupported file manager.

**Comment by mirkobrombin** [comment]
What is the status of this?

**Comment by axtloss** [comment]
The main thing blocking this currently is the file filter to only allow dropping msi and exe files, whenever I try to add the filter it completely blocks every single file from being dropped

**Comment by mirkobrombin** [comment]
Ok I'll take a look

**Comment by axtloss** [comment]
I added a filter to only allow exe and msi files to be ran, this should be ready to merge/review now

**Review by mirkobrombin — APPROVED** [review]

**Comment by mirkobrombin** [comment]
Looks good, can be merged (after fixing the conflict)

**Comment by axtloss** [comment]
Fixed all the conflicts, should be ready to merge now

**Pull request merged**
