### PR TITLE
frontend: Revamp Import

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
This removes the redundant Import page with entries in the primary menu.

image

- ~~Depends on https://github.com/bottlesdevs/Bottles/pull/2749~~
- Closes https://github.com/bottlesdevs/Bottles/issues/2470

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] UI

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Locally

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
I'm getting this error:

```py
10:44:18 (ERROR) Error while running async job: <function BackupManager.import_backup at 0x7fd5ab6f7400>
	Exception: 'NoneType' object has no attribute 'create_bottle_from_config'
 
  File "/var/home/TheEvilSkeleton/Projects/Bottles/build/share/bottles/bottles/frontend/utils/threading.py", line 61, in __target
    result = self.task_func(*args, **kwargs)
  File "/var/home/TheEvilSkeleton/Projects/Bottles/build/share/bottles/bottles/backend/managers/backup.py", line 133, in import_backup
    if config_load.status and manager.create_bottle_from_config(config_load.data):
Traceback (most recent call last):
  File "/var/home/TheEvilSkeleton/Projects/Bottles/build/share/bottles/bottles/frontend/main.py", line 352, in finish
    if result.status:
AttributeError: 'AttributeError' object has no attribute 'status'

```

**Comment by TheEvilSkeleton** [comment]
@Kinsteen can you link to the MR that blocks this?

**Comment by StoneMoe** [comment]
> I'm getting this error while trying to import a configuration:

This is caused by a piece of overlooked code during backend rewrite, fixing in another PR.

**Comment by TheEvilSkeleton** [comment]
Closing this as I won't be working on it anymore

**Pull request closed without merging**
