### PR TITLE
main: Exit on non-sandboxed environments

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
For context: https://usebottles.com/posts/2022-06-07-an-open-letter/ and https://github.com/bottlesdevs/Bottles/issues/2345

It's been 2 years, yet we've seen several cases of distributions fucking up Bottles one way or another, so it's best to protect future users by exiting on non-sandboxed environments.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by mirkobrombin** [comment]
I wonder if this should also be displayed graphically :thinking:

**Comment by TheEvilSkeleton** [comment]
Good idea

**Comment by TheEvilSkeleton** [comment]
I'll also add a check in meson

**Review by mirkobrombin — APPROVED** [review]
LGTM

**Comment by tim77** [comment]
At this point Bottles is not even open source. You should change license to proprietary. 

> Free and open-source software (FOSS) is software that is available under a license that **grants the right to use, modify, and distribute the software,** modified or not, to everyone free of charge.

https://en.wikipedia.org/wiki/Free_and_open-source_software

**Comment by jamiethecat** [comment]
> At this point Bottles is not even open source. You should change license to proprietary.
> 
> > Free and open-source software (FOSS) is software that is available under a license that **grants the right to use, modify, and distribute the software,** modified or not, to everyone free of charge.
> 
> https://en.wikipedia.org/wiki/Free_and_open-source_software

You can still use, modify, and distribute the software.

**Comment by Kellegram** [comment]
> At this point Bottles is not even open source. You should change license to proprietary.
> 
> > Free and open-source software (FOSS) is software that is available under a license that **grants the right to use, modify, and distribute the software,** modified or not, to everyone free of charge.
> 
> https://en.wikipedia.org/wiki/Free_and_open-source_software

Reading comprehension is a long lost skill nowadays huh.

**Comment by Kellegram** [comment]
> > > At this point Bottles is not even open source. You should change license to proprietary.
> > > > Free and open-source software (FOSS) is software that is available under a license that **grants the right to use, modify, and distribute the software,** modified or not, to everyone free of charge.
> > > 
> > > 
> > > https://en.wikipedia.org/wiki/Free_and_open-source_software
> > 
> > 
> > Reading comprehension is a long lost skill nowadays huh.
> 
> Submitting such PR's without achieving the main goal of this PR since distro maintainers could easily revert this patch - it's probably for very smart and skilled people only. So the next step is closing source of Bottles I guess? FOSS nowadays.
> 
> Just some comments from happy Bottles users of non-flatpak build:
> 
> > As a user, this is frightening. I could never get Flatpak Bottles to work properly on my Fedora system; I gave up after 12+ hours of trying.
> > The only Bottles that worked for me is the RPM package that you maintain. Thank you for keeping it alive.
> 
> Sounds like a great comprehension and skill of Bottles devs. Keep it up.

The fact that distro maintainers can reverse it directly proves that the project is still FOSS and makes your reply nonsensical at best. Developers can do what they think is right with their code and if they can discourage terrible packaging of their stuff, it makes sense. Maintainers in the end can also choose to badly package foss software, it's unfortunate but this PR is not attempting to block that, just discourage it. 

You can cherry pick comments as much as you like, there's no context to it and it's entirely possible the user is entirely at fault there and there is something wrong with their setup as a whole (which is often the case). Typically it's native packaging that causes problems, flatpaks are far more consistent. If we want to cherry pick random comments then here we go, I had nothing but trouble with native packaging of Bottles, it never worked properly for me and re-running bottles would not give me consistent results, unlike the Flatpak version ¯\_(ツ)_/¯. Individual experiences aren't representative of the majority, context matters.

**Comment by tim77** [comment]
> The fact that distro maintainers can reverse it directly proves that the project is still FOSS and makes your reply nonsensical at best. 

The fact that you hardly know [what free software is](https://en.wikipedia.org/wiki/Free_and_open-source_software#Four_essential_freedoms_of_Free_Software) or if you doing this intentionally then just proves that Bottles is not free software at this point with this PR. 

**Four essential freedoms of Free Software**

- The freedom to run the program as you wish, for any purpose (freedom 0).

There is no freedom anymore after this PR merged. App will **NOT** run without modifying code. Developers intentionally prevent running app for non-flatpak builds. If user decide to compile app yourself for non-flathub environment - app will not work. 

- The freedom to redistribute copies so you can help others (freedom 2).

Developers not allowing doing this and making intentional life harder for downstream packagers. 

- The freedom to distribute copies of your modified versions to others (freedom 3). By doing this, you can give the whole community a chance to benefit from your changes. Access to the source code is a **precondition** for this.

The access to source code is just a precondition. This does not mean that this is FOSS app just because the source code is open. So since license is still allows to modify and redistribute the app this PR is just nonsensical at best. The only way to achieve the goal of this PR is changing license to proprietary.

**Comment by TheEvilSkeleton** [comment]
> At this point Bottles is not even open source. You should change license to proprietary.

We won't, but even if we wanted to, we literally can't. We don't hold copyright of the entire project (only contributors do); there aren't any additional license or clause that contributors must sign to transfer copyright, so Bottles is here to stay under the GPLv3 :)

> > Free and open-source software (FOSS) is software that is available under a license that **grants the right to use, modify, and distribute the software,** modified or not, to everyone free of charge.
> 
> https://en.wikipedia.org/wiki/Free_and_open-source_software

You folks are free to fork, modify, redistribute, and break the software like you've been doing since the dawn of time, just as much as we're allowed to bump these requirements during build time and protect ourselves from burning out from problems that are completely out of our control. We published [*Please don't unofficially ship Bottles in distribution repositories*](https://usebottles.com/posts/2022-06-07-an-open-letter/) more than 2 years ago, but we haven't noticed a significant improvement. And taking https://github.com/bottlesdevs/Bottles/issues/2345 into consideration, it's clear to me that you folks (Bottles RPM maintainers) don't really care about the situation, especially when Bottles is supposed to run in a sandboxed environment, which the RPM doesn't, so why should we care about your clearly unsupported and even completely insecure case? It seems to me that you folks instead just want to satisfy your packaging fetish. I took a year off because I was burned out from the whole silly situation that could have been easily prevent had you discontinued the package and moved on.

> Submitting such PR's without achieving the main goal of this PR since distro maintainers could easily revert this patch - it's probably for very smart and skilled people only. So the next step is closing source of Bottles I guess? FOSS nowadays.

This literally contradicts what you wrote earlier, but either way, that's fine by me. If it bumps the requirements to something that is completely unfeasible for distribution packages, that's not my problem. If it's something that requires you to fight the software to make it work in an environment that wasn't designed to run on, then you should be asking yourself if the software is the problem, or you, the person who's trying to misuse the format.

> There is no freedom anymore after this PR merged. App will **NOT** run without modifying code. Developers intentionally prevent running app for non-flatpak builds. If user decide to compile app yourself for non-flathub environment - app will not work.

It should work with [Fedora Flatpaks](https://fedoramagazine.org/an-introduction-to-fedora-flatpaks/), so no, that's just completely wrong. The only thing I'm currently not fond of is making Flatpak a hard dependency during the build process, as I want to make it allowable in alternate sandbox formats. The least we can do for now is using [`Xdp.Portal.running_under_sandbox ()`](https://libportal.org/type_func.Portal.running_under_sandbox.html) as opposed to [`Xdp.Portal.running_under_flatpak ()`](https://libportal.org/type_func.Portal.running_under_flatpak.html).

> Developers not allowing doing this and making intentional life harder for downstream packagers.

Of course we are. Bottles isn't meant to run with insecure formats.[^1] We were really nice by publishing a letter and not doing anything at the beginning, but it was left ignored for years without any substantial improvements. We can't fix your stupidity and ignorance, so the next best thing is to prevent them from leaking into Bottles.

Besides, the use of buildsystems inherently makes the whole packaging process difficult.[^2] They're literally made to check compatibility between software and libraries to install everything appropriately. The moment a check is added, no matter how insignificant it may be, it's now more difficult to package. The only difference is that our requirements and standards are much higher than ever, making them incompatible with your use case. If you still believe that Bottles is no longer FOSS, then I regret to inform you that no software should be regarded as FOSS in your perspective.

---

Anyway, I'm locking this MR because we've made it _very clear_ about our opinions and even went to the length of explaining _why_. Bottles is not made for Fedora. It's made for sandboxed formats like Flatpak.

[^1]: Not saying Flatpak is secure, but it's the most secure option we currently have
[^2]: but are really convenient at the same time

**Comment by mirkobrombin** [comment]
> At this point Bottles is not even open source. You should change license to proprietary.
> 
> > Free and open-source software (FOSS) is software that is available under a license that **grants the right to use, modify, and distribute the software,** modified or not, to everyone free of charge.
> 
> https://en.wikipedia.org/wiki/Free_and_open-source_software

Now read what you quoted again.

**Pull request merged**
