### PR TITLE
fix: Steam and Proton usage

### LINKED ISSUE #2850: [Bug]: Inconsistent capitialization can lead to broken/missing runners
### Describe the bug

When Bottles downloads certain runners, their capitalization is slightly different from what Bottles was expecting and so will lead to the confusing behavior and the runner not working correctly.

Bottles shouldn't be tripped up by this capitalization mismatch. A possible solution would be renaming the resulting runner folder whatever name Bottles expects it to be.

### To Reproduce

1. Download the ge-proton7-51 runner
2. Click on "Browse files" for the runner
3. Bottles can't show the files, "OpenURI portal not installed"
4. Restart Bottles
5. Bottles no longer thinks ge-proton7-51 is installed
6. Rename the "GE-Proton7-51" runner folder to "ge-proton7-51"
7. Restart Bottles
8. Both problems are now fixed but the runner will no longer run ([Bottles is checking for "Proton"](https://github.com/bottlesdevs/Bottles/blob/775939488296fdb570856981cbfea59b663cf119/bottles/backend/wine/winecommand.py#L415))

### Package

Flatpak from Flathub

### Distribution

Ubuntu 22.10

### Debugging Information

```shell
Official Package: true
Version: '51.5'
DE/WM: plasma
Display:
    X.org: true
    X.org (port): :0
    Wayland: false
Graphics:
    vendors:
        nvidia:
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-525-105-17/extra/nvidia/wine
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 5.19.0-38-generic
Disk:
    Total: 16785584128
    Free: 16785416192
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 11.5GiB
Bottles_envs: null
```

### Troubleshooting Logs

_No response_

### Additional context

_No response_

### LINKED ISSUE #2952: [Bug]: Invalid Steam Proton path
### Describe the bug

Bottles has stopped listing proton prefixes. When I run `flatpak run com.usebottles.bottles` in terminal it outputs:
```
00:17:12 (ERROR) /app/share/steam/compatibilitytools.d/Proton-GE/l is not a valid Steam Proton path 
00:17:12 (WARNING) A Steam prefix was found, but there is no Proton for it: 548430, skipping… 
00:17:12 (ERROR) /app/share/steam/compatibilitytools.d/Proton-GE/l is not a valid Steam Proton path 
00:17:12 (WARNING) A Steam prefix was found, but there is no Proton for it: 39510, skipping… 
00:17:12 (WARNING) A Steam prefix was found, but there is no Proton for it: 548430, skipping… 
00:17:12 (WARNING) A Steam prefix was found, but there is no Proton for it: 39510, skipping…
```
I have noticed one more thing, possibly related. After installing the "ge-proton-8-6" runner and revisiting the Preferences and then Runners tab, I am able to install "ge-proton-8-6" once again. The "Download & Install" button is displayed instead of "Browse files". However, upon restarting Bottles, the following message appears in the terminal:
```
00:36:47 (INFO) Runners found:
         - soda-7.0-9
         - wine-ge-proton8-10
         - GE-Proton8-6
         - sys-wine-8.0
```
ge-proton-8-6 exists in `.var/app/com.usebottles.bottles/data/bottles/runners/` and I can use it as runner in my bottles.

I have tried to reinstall Bottles with deleting all leftover folders and it didn't help at all.

### To Reproduce

1. Turn on "Steam Proton Prefixes".
2. Restart Bottles.

For the second part:
1. Go to the Preferences->Runners tab.
2. Install ge-proton-8-6
3. Close Preferences and revisit Runners tab.
4. ge-proton-8-6 should be possible to install again.

### Package

Flatpak from Flathub

### Distribution

Debian 12 Bookworm 

### Debugging Information

```shell
Official Package: true
Version: '51.6'
DE/WM: plasmawayland
Display:
    X.org: true
    X.org (port): :1
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
Kernel:
    Type: Linux
    Version: 6.1.0-10-amd64
Disk:
    Total: 16785051648
    Free: 16784896000
RAM:
    MemTotal: 31.3GiB
    MemAvailable: 25.2GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
(process:2): Gtk-WARNING **: 00:36:45.885: Locale not supported by C library.
        Using the fallback 'C' locale.
00:36:46 (INFO) Bottles Started! 
00:36:47 (INFO) Performing Bottles checks… 
00:36:47 (INFO) Dxvks found:
         - dxvk-2.2
 
00:36:47 (INFO) Vkd3ds found:
         - vkd3d-proton-2.9
 
00:36:47 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.3
 
00:36:47 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
00:36:47 (INFO) Runners found:
         - soda-7.0-9
         - wine-ge-proton8-10
         - GE-Proton8-6
         - sys-wine-8.0
 
00:36:47 (INFO) Bottles found:
         - Battle.net
 
00:36:47 (ERROR) /app/share/steam/compatibilitytools.d/Proton-GE/l is not a valid Steam Proton path 
00:36:47 (WARNING) A Steam prefix was found, but there is no Proton for it: 548430, skipping… 
00:36:47 (ERROR) /app/share/steam/compatibilitytools.d/Proton-GE/l is not a valid Steam Proton path 
00:36:47 (WARNING) A Steam prefix was found, but there is no Proton for it: 39510, skipping… 
00:36:47 (WARNING) A Steam prefix was found, but there is no Proton for it: 548430, skipping… 
00:36:47 (WARNING) A Steam prefix was found, but there is no Proton for it: 39510, skipping… 
00:36:47 (INFO) Catalog dependencies loaded 
00:36:47 (INFO) Catalog installers loaded 
00:36:47 (INFO) Catalog components loaded
```

### Additional context

EDIT: I run steam flatpak with proton-ge community (com.valvesoftware.Steam.CompatibilityTool.Proton-GE) and I have also manually installed proton-ge following GloriousEggroll manual instruction
`tar -xf GE-ProtonVERSION.tar.gz -C ~/.var/app/com.valvesoftware.Steam/data/Steam/compatibilitytools.d/`
and I can play games from steam just fine with both.

### PR DESCRIPTION
**Pull request by koplo199**
# Description
Fixes #2952
Fixes #2850

To completely fix those issues, `Proton-GE` runners manifests should be updated in the [components](https://github.com/bottlesdevs/components) repository. It is independent from this PR and will not require further `Bottles` code change.

I described what the issue is and how to fix it in the linked issues, pasting those comments for reference: 
>There is two bugs here.
The first one is on the [component](https://github.com/bottlesdevs/components) side and match what you described: there is a mismatch between the component name (lower-case) and the extracted component directory (which contains capitalized letters). 
Concerning the fix: should we change the extracted folder name to lower-case, or the component name to include those capitalized letters? Capitalizing (e.g. `ge-proton7-51` to `GE-Proton7-51`) will require the least changes/hacks, and would be more consistent with the upstream name, but I'll submit a PR there based on the decision of a maintainer.
The second bug is on the Bottles side and is actually identical to what's described in #2593, so the fix would be the same. What is happening is that the backed still uses the name of the component to decide if a runner is Proton or Wine, instead of what's included in its manifest. And it causes issues with Wine runners which contains `[pP]roton` in their name, like Kron4ek's [wine-proton-8.0-1-amd64](https://github.com/Kron4ek/Wine-Builds/releases/tag/proton-8.0-1) or GloriousEggroll's [Wine-GE-Proton7-43](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-43).

_Originally posted by @koplo199 in https://github.com/bottlesdevs/Bottles/issues/2850#issuecomment-1519078006_

>It's probably not a permission issue, I think there's two different causes to the bug.
First, in Bottles, the code responsible for detecting the proton path is not robust at all: 
https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/bottles/backend/managers/steam.py#L194
It seems Bottles expect the third line to always end by `/lib/`, thus stripping those five characters to retrieve the path. But here, at least with the `Proton-GE` installed by flatpak, this line ends with `/lib32/`, which would be seven characters. Stripping only five would give `Proton-GE/l` and this is exactly what shows in the logs.
The Bottles code definitively needs a more reliable method for retrieving the path, but I strongly suspect using the `lib32`/`lib` folder structure instead of the regular `lib`/`lib64` is also a bug on its own as it may be the source of other [issues](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE/issues/48).
Somewhat related note: there is still other issues that needs to be fixed for a flawless steam experience, since the 8.0 version Proton is using the [sniper](https://github.com/ValveSoftware/Proton/commit/28aeb63901c47dca236ccfb4db2f111086338c59) runtime instead of the much older `soldier` one, but Bottles [does not support it](https://github.com/bottlesdevs/Bottles/blob/9132667ae41a04769b286a09471306ba4deed980/bottles/backend/managers/runtime.py#L136-L145) at the moment.

_Originally posted by @koplo199 in https://github.com/bottlesdevs/Bottles/issues/2952#issuecomment-1630361702_
            

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Tested with flatpak build artifacts

### CODE REVIEW

**Comment by koplo199** [comment]
@pszabunko Could you confirm it fixes the issue for you? Please also submit log entries containing `Steam` or `Proton`.

The build artifact can be downloaded [here](https://github.com/bottlesdevs/Bottles/suites/14242988463/artifacts/799839386), if I'm not mistaken it can be installed with a regular `flatpak install bottles-x86_64.flatpak` upon unzipping.

**Comment by koplo199** [comment]
Ah my bad, I forgot the `.strip()` method change before commiting, that is why the Proton path is not detected correctly, it should be fine now.

Thanks for the logs, it seems the new method for detecting a Proton prefix is working correctly.

Last thing to check is that the Steam runtime is now chosen accordingly to what's defined in the `toolmanifest.vdf`, what we're looking for here is the following line in the logs: `Using Steam runtime [...]`, maybe a game should be started to trigger it?

The new build artifact should be available soon [here](https://github.com/bottlesdevs/Bottles/actions/runs/5535743186?pr=2961).

**Comment by pszabunko** [comment]
It's back to the original probem: working for runners installed manually or with protonup-qt and not working for `com.valvesoftware.Steam.CompatibilityTool.Proton-GE` from flatpak.
```
(process:2): Gtk-WARNING **: 00:26:15.291: Locale not supported by C library.
        Using the fallback 'C' locale.
00:26:15 (INFO) Bottles Started! 
00:26:16 (INFO) Performing Bottles checks… 
00:26:16 (INFO) Steam path doesn't exist, creating now. 
00:26:16 (INFO) Dxvks found:
         - dxvk-2.2
 
00:26:16 (INFO) Vkd3ds found:
         - vkd3d-proton-2.9
 
00:26:16 (INFO) Nvapis found:
         - dxvk-nvapi-v0.6.3
 
00:26:16 (INFO) Latencyflexs found:
         - latencyflex-v0.1.1
 
00:26:16 (INFO) Runners found:
         - soda-7.0-9
         - sys-wine-8.0
 
00:26:16 (WARNING) A Steam prefix was found, but it is a Proton one: 1493710, skipping… 
00:26:16 (WARNING) A Steam prefix was found, but it is a Proton one: 2348590, skipping… 
00:26:16 (ERROR) /app/share/steam/compatibilitytools.d/Proton-GE is not a valid Steam Proton path 
00:26:16 (WARNING) A Steam prefix was found, but there is no Proton for it: 39510, skipping… 
00:26:16 (WARNING) A Steam prefix was found, but it is a Proton one: 1887720, skipping… 
00:26:16 (WARNING) A Steam prefix was found, but it is a Proton one: 1493710, skipping… 
00:26:16 (WARNING) A Steam prefix was found, but it is a Proton one: 2348590, skipping… 
00:26:16 (WARNING) A Steam prefix was found, but there is no Proton for it: 39510, skipping… 
00:26:16 (WARNING) A Steam prefix was found, but it is a Proton one: 1887720, skipping… 
00:26:16 (INFO) Catalog installers loaded 
00:26:16 (INFO) Catalog dependencies loaded 
00:26:16 (INFO) Catalog components loaded 
```
However, it looks like it gets proton from flatpak directory right this time `/app/share/steam/compatibilitytools.d/Proton-GE`, but it checks for it on my system instead of `com.valvesoftware.Steam.CompatibilityTool.Proton-GE` flatpak or however com.valvesoftware.Steam flatpak does.

**Comment by koplo199** [comment]
[This](https://github.com/bottlesdevs/Bottles/suites/14260015187/artifacts/801114936) revision should finally fix the `Proton-GE` detection, however I'm more intrigued by the `Using Steam runtime scout` line. Given the `toolmanifest.vdf` you linked, it should clearly uses the `sniper` runtime, and not `scout`.

Does the path `~/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/SteamLinuxRuntime_sniper` exists? If not, then this is "normal" (well, not really since Steam is supposed to download any runtime its components need but at least it isn't an issue within Bottles), and hopefully downloading it with `flatpak run com.valvesoftware.Steam steam://install/1628350` should make it use it on the next run.

**Comment by pszabunko** [comment]
```
flatpak run com.usebottles.bottles 
bwrap: Can't mkdir parents for /app/share/steam/compatibilitytools.d: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by koplo199** [comment]
Sorry, it was once again a one-liner not commited, the missing part was:
` - mkdir -p /app/share/steam/compatibilitytools.d` in the manifest.

Could you confirm it is now correctly working on your end too?

Note: I reverted the update of the runtime to keep this PR entirely focused on the fix.

**Comment by pszabunko** [comment]
Where do I download new version?

**Comment by koplo199** [comment]
It can be downloaded [here](https://github.com/koplo199/Bottles/suites/14282835151/artifacts/802817583).

**Comment by pszabunko** [comment]
It runs now, but still cannot find com.valvesoftware.Steam.CompatibilityTool.Proton-GE
```
20:38:22 (ERROR) /app/share/steam/compatibilitytools.d/Proton-GE is not a valid Steam Proton path 
```

**Comment by koplo199** [comment]
It seems the flatpak version, unlike its official counterpart, does not define `compatmanager_layer_name` in its manifest, which 
was used for the Proton detection. I added another check using the `commandline` entry, which is that time defined in the flatpak manifest.

Looking at that manifest, it also don't define a `require_tool_appid`, and thus [defaults to scout for its runtime as it should](https://github.com/ValveSoftware/Proton/commit/679a4340acf059663b16cfebac87be9e2da18a30). The manifest is clearly misconfigured, Proton version >= 8.0 are built and meant to be run under the `sniper` runtime.

**Comment by pszabunko** [comment]
It's currently displaying all the Steam prefixes, and there are no errors during the startup.

**Comment by koplo199** [comment]
That is nice to hear, thank you @pszabunko for helping debugging these issues.

This should be ready for review.

**Comment by mirkobrombin** [comment]
Sorry @koplo199 I forgot about this PR. Can you please re-base? The code looks good to me.

**Pull request merged**
