### PR TITLE
Full Translation in french

### PR DESCRIPTION
**Pull request by AkechiShiro**
# Description
All strings in English were translated in French to the best of my ability, any suggestion on the current translation to make it better is welcomed !

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
I didn't test the changes (since I just discovered this tool a day ago, but I will definitely try it out soon enough and report here any test/bug I saw if there are any), but I suppose that such a change (support a new language) will not break the execution of the program.

### CODE REVIEW

**Review by mirkobrombin — APPROVED** [review]

**Comment by mirkobrombin** [comment]
Thanks for your work, it is much appreciated.

**Comment by AkechiShiro** [comment]
Thanks, it was a pleasure to help, also thanks for working on this tool, I think this tool is a very good idea to manage Wineprefix (this kind of tool to me is missing at the moment, Lutris and POL is not really tailored to the task), I think this tool should be more known, I stumbled across it whilst looking at wine packages in the AUR, I'm looking forward to it gaining more features, maybe I could help by contributing.

**Comment by mirkobrombin** [comment]
> I stumbled across it whilst looking at wine packages in the AUR, I'm looking forward to it gaining more features, maybe I could help by contributing.

Thanks and you are welcome!

**Review by francescomasala — APPROVED** [review]
Excellent work! Congratulations

**Pull request merged**
