### PR TITLE
frontend: Use generic names to improve user-friendliness

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
This MR changes most titles and subtitles of preferences, using generic names. Many projects use names that do not really explain their intention, which makes it difficult to understand. This makes it more user friendly as these new titles and subtitles better convey the intention of said preferences.

Fixes https://github.com/bottlesdevs/Bottles/issues/1837.

~~Blocked by https://github.com/bottlesdevs/Bottles/pull/2041 and https://github.com/bottlesdevs/Bottles/pull/2043~~.

Example:

image

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Locally

### CODE REVIEW

**Review by mirkobrombin — APPROVED** [review]

**Comment by TheEvilSkeleton** [comment]
@jannuary since you added the `Requires evaluation` tag, what do you think so far?

**Comment by jannuary** [comment]
I am not entirely convinced this makes it any clearer what these settings do and what effects they have.
In particular:
- DXVK and VKD3D seem to replace one jargonism with another. That said, I'm not sure it could be portrayed better, aside from describing what it does instead of what it is (e.g. Translate DirectX to Vulkan) Maybe removing "9/10/11" but keeping "12" would help? 
- DLSS seems fine to me - however I'm not sure if duplicating "Deep Learning Super Sampling" and mentioning NVAPI is merited.
- "Reduce Input Latency" makes no sense. Ditto as for "Reduce Audio Latency" - why would you ever increase latency?
- "Vulkan Post-Processing Layer" isn't English. Also, how does one "enhance shaders"?

**Comment by TheEvilSkeleton** [comment]
I made some edits but I'm not sure if it makes things any clearer.

**Comment by mirkobrombin** [comment]
I prefer the prior version. Now title and subtitle say the same thing:
```
      title: _("Translate DirectX to Vulkan");
      subtitle: _("Translate from Direct3D 9, 10 and 11 to Vulkan using DXVK.");
```

**Comment by TheEvilSkeleton** [comment]
I prefer that one as well.

**Comment by mirkobrombin** [comment]
I would like to avoid postponing these changes again, they are fine for me.

**Comment by TheEvilSkeleton** [comment]
If there's something wrong, then we'll just reword some things here and there.

**Pull request merged**
