### PR TITLE
bottles V1: move to github actions

### PR DESCRIPTION
**Pull request by cat-master21**
# Description
This moves away from Travis Ci and uses GitHub Actions. In addition this changes a dependency
wine-stable to wine, as this wine-stable is only on Ubuntu and is just a dummy deb with wine as a dependency.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Thanks for your contribution!

**Comment by mirkobrombin** [comment]
Seems not working [build](https://github.com/bottlesdevs/Bottles/runs/5566185562?check_suite_focus=true)
bottles.$GITHUB_SHA.deb doesn't match any files

**Comment by cat-master21** [comment]
Alright, I'll send another pr later @mirkobrombin.

**Comment by cat-master21** [comment]
The fix pr is at: https://github.com/bottlesdevs/Bottles/pull/1207 now @.

**Comment by cat-master21** [comment]
The fix pr is at: https://github.com/bottlesdevs/Bottles/pull/1207 now @mirkobrombin.

**Comment by mirkobrombin** [comment]
Thanks

**Pull request merged**
