### PR TITLE
Welcoming contact field

### PR DESCRIPTION
**Pull request by comradekingu**
# Description
Non-authoritarian means of contact.

Fixes #(issue)
Helps not misrepresent people and the freedom enjoyed by contributing.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.

Works great in this project.

### CODE REVIEW

**Comment by mirkobrombin** [comment]
How is removing our CoC an improvement?

**Comment by fries1234** [comment]
code of conducts arent authoritarian. gnomes code of conduct is actually quite based ngl.

**Comment by fries1234** [comment]
i dont see how removing the detailed document saying "yo dont be a bigot and be respectful" is gonna make the project better. if you think a code of conduct saying you shouldnt be a bigot is authoritarian (which its not btw), maybe the problem is you.

**Comment by comradekingu** [comment]
@mirkobrombin
It removes an expectancy from what is actual navigation of social hierarchy.
It then makes everyone "subject to the Code of Conduct".
The sections on considerations, being welcoming, and friendly are additionally meaningless.
It is closed immediately, following maintainer questioning.

Contributors helping the project for free without it weren't even asked.
It is far-encroaching, instrumenting a policing of private conversations.
It moves this created encroachment on principles of freedom into the hands of the GNOME foundation.
There is no reason to suggest this entity would handle matters better.

In addition to being particularly badly written, it then singles people out for their immutable characteristics.
This is the exact opposite of what cognitive behavioural therapy would suggest, the most potent tool in clinical psychology outside of pharmaceuticals.
It dictates compelled speech by mandating "inclusive language", again something with zero accolades to its name.
"Jokes" are also banned, which is affirmation that intent is not important.
Then it gets into things redundant to law, which is a curious position of self-aggrandising its character.
It isn't actually in a position to do so, but thinks so highly of itself as to put itself over community.
Sexuality is outright banned on account of banning sexual advances.
This is not how humanity works.

>The GNOME community prioritizes marginalized people's safety over privileged people's comfort. The committee will not act on complaints regarding:

The GNOME foundation finds itself in a position of being the arbiter of deciding how to distinguish between groups.
Outright discrimination (following words to the contrary), but also an escalation of assumed power.

> * "Reverse"-isms, including "reverse racism," "reverse sexism," and "cisphobia"
…
 * Criticizing racist, sexist, cissexist, or otherwise oppressive behaviour or assumptions

I would like to complain about any and all things, with nothing off limits. Additionally why these are not responded to I find wanting.
For someone having to add the word "reverse" to their claims of non-action of responding to discrimination of their own making, is telling.

**Comment by fries1234** [comment]
whats wrong with banning sexual advances, sexual harassment is bad yknow.

also its saying its banning sexually charged "jokes" (which arent jokes btw, theyre sexual harassment). they never said they were banning jokes.

also you shouldnt be making sexual comments on a github pull request anyways.

**Comment by comradekingu** [comment]
@fries1234 
Just to specifically respond to your concerns.

>whats wrong with banning sexual advances, sexual harassment is bad yknow.

The two are not one and the same. One is natural, and the other is illegal.
If not making a sexual pass at someone, there is no true knowing how they respond.
You get one, and it is predicated on making yourself somewhat vulnerable as subject to rejection.
Sexual selection is possibly the most powerful human fundamental aspect, and a text-file doesn't change it like no
text-file has had success changing it in the past. It is a 100% spectacular failure rate.

>also its saying its banning sexually charged "jokes" (which arent jokes btw, theyre sexual harassment). they never said they were banning jokes.

I read that as "jokes", because it says so. It doesn't say "sexual harassment", but it does say "sexualized environment".
This means any complaint by anyone is enough, and everything is above board here.
I argue that the distinction you are trying to make is an interpretation, and it is particularly hard to defend or even discern from what could be a clarifying text.

>also you shouldnt be making sexual comments on a github pull request anyways.

I posit that you already knew this wasn't the particular forum to do so.
It is however impossible to prevent it anywhere humans interact in any capacity.
That being the case, it is another matter entirely to attemptedly ban it.
When professionalism is valued above community values, humanity dies in predictably awful ways.

>Authoritarianism: adjective
favoring complete obedience or subjection to [authority](https://www.dictionary.com/browse/authority) as opposed to individual freedom: authoritarian principles; authoritarian attitudes.
of or relating to a governmental or political system, principle, or practice in which individual freedom is held as completely subordinate to the power or [authority](https://www.dictionary.com/browse/authority) of the state, centered either in one person or a small group that is not constitutionally accountable to the people.

There is no oversight here.

exercising complete or almost complete control over the will of another or of others: an authoritarian parent.
noun
a person who favors or acts according to authoritarian principles.

Governing sexuality and freedom of speech is nearing complete control.

>If a participant engages in behavior that violates this code of conduct, the GNOME Code of Conduct committee may take any action they deem appropriate

Is Carte Blanche authoritarianism. It just needs very vague reasoning, like 
>prioritizes marginalized people's safety over privileged people's comfort

>We want all participants in the GNOME community have the best possible experience they can.

and so on

Additionally, it allows no leeway.

> **Influencing or encouraging inappropriate behavior.** If you influence or encourage another person to violate the Code of Conduct, you may face the same consequences as if you had violated the Code of Conduct.

>bigot
noun
A person who is obstinately or unreasonably attached to a belief, opinion, or faction, especially one who is prejudiced against or antagonistic towards a person or people on the basis of their membership of a particular group
Synonyms: prejudiced person, sectarian, chauvinist, partisan, dogmatist

I think a more compelling non-bigoted appeal could be made by forgoing instrumenting dictating language or actively treating discrimination of people as a reason to do whatever deemed reasonable.

I included the synonyms, because I try to administrate the opposite in rules for all.

The document this replaced, which I want to reinstate was entirely non-bigoted.
It doesn't assume ability to respect privacy and constructivist, but those are the limits.
They are further limited by ability, and that is an appeal to the potential in working together.
It may or may not be that someone is capable, but then again I don't have to make that point.
It de-escalates not only in dealing with ones own problems, but also not wasting maintainer time if it is possible.
The assumption here is that any problem solved is best fixed by someone with all the details, rather than someone with
a written account of the problem. It is not a place to take out grievances, as opposed to the ample opportunity found in interpretation.
Maybe the problem is me. Make that case.

**Comment by TheEvilSkeleton** [comment]
What the fuck

**Pull request closed without merging**
