### PR TITLE
frontend: Remove FileChooser class

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
This removes the FileChooser class to avoid using and being blocked by wrappers.
I also added filters for exe and msi files.

Closes https://github.com/bottlesdevs/Bottles/issues/2466

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] Locally

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
https://github.com/bottlesdevs/Bottles/pull/2496/commits/fbc3ee04da256761f9f5260e2abad6adfd1cdf2a and https://github.com/bottlesdevs/Bottles/pull/2496/commits/5fb5d3acd12725620646b144fb17fa812225f43b need testing.

**Comment by mirkobrombin** [comment]
Got an exception trying to install Ableton from the installers section:
```
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/windows/installer.py", line 62, in __choose_path
    parent=self.window,
AttributeError: 'LocalResourceEntry' object has no attribute 'window'
```

**Comment by TheEvilSkeleton** [comment]
Those two errors are reproducible in the stable branch. I'll try to fix the first problem, but the second is out of scope.

**Comment by TheEvilSkeleton** [comment]
@mirkobrombin can you test again? It works for me.

**Comment by mirkobrombin** [comment]
> Those two errors are reproducible in the stable branch. I'll try to fix the first problem, but the second is out of scope.

I don't see it in the stable branch

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
