### PR TITLE
51.10

### LINKED ISSUE #3098: Update to GNOME 45, Bottles 51.10
GNOME 45 was released not too long ago, and we should probably update to it so we can nab some [glib-related issues](https://github.com/bottlesdevs/wine/issues/54) along the way. While we're at it, bump the Bottles version; once https://github.com/bottlesdevs/Bottles/pull/2840 lands, we can make 51.10. 

Also see https://github.com/bottlesdevs/Bottles/pull/2977 so we can land it. 

I'd do a 52 release, but we need more activity on [the 52 milestone](https://github.com/bottlesdevs/Bottles/milestone/20)

@koplo199 would you mind making the pull request for the release and Bottles update, as well as testing the linked pull request(s)? Sorry to push so much onto you.

### PR DESCRIPTION
**Pull request by koplo199**
Fixes #3098

### CODE REVIEW

**Comment by koplo199** [comment]
Well, that was more challenging that I initially though.

For testing purpose, [here](https://github.com/bottlesdevs/Bottles/suites/16610923079/artifacts/949004558) is the Flatpak build artifact. Nothing to report at the moment.

**Comment by mirkobrombin** [comment]
Is this PR related to #3117? If so, which one should be merged as first?

**Comment by koplo199** [comment]
@mirkobrombin The two PR's are not related (as in there's no hard dependency between the two), merging #3117 (and #3112, #3101) first would just allow these fixes to be part of the 51.10 release

**Comment by koplo199** [comment]
Updated gamemode to the latest 1.8 version (and removed the now unnecessary build patch)

**Comment by koplo199** [comment]
May Santa bring the 51.10 release in his bag for christmas? (with #3204 merged just before)

**Comment by mirkobrombin** [comment]
I'm busy on vanilla os and can't test. If you confirm that everything is working correctly I can merge both

**Comment by koplo199** [comment]
@mirkobrombin Just retested with a local build, and from that testing I confirm it is working correctly

**Comment by mirkobrombin** [comment]
> @mirkobrombin Just retested with a local build, and from that testing I confirm it is working correctly

Thanks, I'll merge https://github.com/bottlesdevs/Bottles/pull/3204 and this then

**Comment by mirkobrombin** [comment]
Ho ho ho merry Christmas

**Comment by koplo199** [comment]
Had no doubt Bottles users were on the nice list, thank you Santa! :flushed:

**Pull request merged**
