### PR TITLE
CI: Build Flatpak

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
# Description
This replaces the Arch CI for Flatpak. Additionally, it also creates .flatpak bundles so we can install and test them.

Closes https://github.com/bottlesdevs/Bottles/issues/2058.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] CI

### CODE REVIEW

**Comment by mirkobrombin** [comment]
I'll test it asap. Can you re-add [build_pkgs_unstable.yml](https://github.com/bottlesdevs/Bottles/pull/2072/files#diff-00cdf1ce72f8acfa8dd3e16bd2659ae8c9a455b43176edb6a3f4c51bc0d3650e) which is being used as reference for the appimage?

**Comment by mirkobrombin** [comment]
Mmh the CI is failing https://github.com/bottlesdevs/Bottles/actions/runs/3067599688/jobs/4954052973

**Comment by TheEvilSkeleton** [comment]
I fail to understand why it fails. I tried validating appstream locally and there is no error.

**Comment by axtloss** [comment]
This appdata issue happens for me too, I always have to either take out all the url tags or use the flatpak builder flatpak instead of a system package

**Comment by mirkobrombin** [comment]
I think the problem is in the version of the package

**Comment by axtloss** [comment]
I got it working by making it remove the url tags from the appdata: https://github.com/axtloss/Bottles/blob/master/.github/workflows/build_flatpak.yml#L21-L23

**Comment by TheEvilSkeleton** [comment]
This removes many important metadata. This is not normal whatsoever.

**Comment by axtloss** [comment]
From what I understand this is just to see if the build succeeds? I don't think removing some url tags from the appdata would be that big of an issue

**Comment by TheEvilSkeleton** [comment]
Marking it as draft because I don't want to remove those URL tags.

**Comment by TheEvilSkeleton** [comment]
Where do I download artifacts?

**Comment by axtloss** [comment]
It should be on the summary page of the action

**Comment by TheEvilSkeleton** [comment]
Alright, it works! Merging.

**Pull request merged**
