### PR TITLE
fix: nvngx.dll not copied under Flatpak, UI consistency

### LINKED ISSUE #1013: DXVK NVAPI does not work (DLSS?)
**Describe the bug**
When enabling dxvk nvapi, dlss does not work

**Installation**
 - Method: Flatpak
 - Version 2022.1.28-trento-3

**To Reproduce**
1. Enable DXVK NVAPI
2. Open a game with DLSS
3. Wont be able to enable DLSS

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 35
 - Display server: Xorg

### PR DESCRIPTION
**Pull request by Kinsteen**
# Description

<details><summary>Old Post</summary>
<p>
NVAPI should be able to disabled. This PR adds a "Disabled" option like dxvk, vkd3d, which can enable/disable NVAPI properly

(somewhat) fixes #1013, by having NVAPI disabled properly while creating a Bottle, and enabling/disabling it will properly update the different DLLs required for NVAPI.
</p>
</details>

This PR started as an UI update, but it is actually unnecessary. This PR now fixes UI updates not propagated properly between NVAPI and the DLSS switch, and fixes the `nvngx.dll` not being copied properly under Flatpak.

Bottles will check at each startup if the nvngx DLLs have changed against the driver-provided ones, and will update the bottle if so.

Thanks Lutris/Proton for their code about the Nvidia library detection!

Still fixes #1013

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. 
Provide instructions so we can reproduce.
- [x] locally, with and without Flatpak

### CODE REVIEW

**Comment by Kinsteen** [comment]
I'm not sure if NVAPI should be enabled by default, why was it commented?

**Comment by mirkobrombin** [comment]
It was causing compatibility issues

**Review by mirkobrombin — APPROVED** [review]

**Comment by Kinsteen** [comment]
Okay, should I revert it?

**Comment by mirkobrombin** [comment]
It's probably better

**Comment by Kinsteen** [comment]
Done

**Comment by Kinsteen** [comment]
Converted to draft as there more changes needed right now

**Comment by Kinsteen** [comment]
See original post, lots have changed

**Comment by Kinsteen** [comment]
Again lots of changes:
- At startup, Bottles will check if the `nvngx.dll` are present and up to date in bottles that have enabled DLSS.
- The detection of the Nvidia DLLs are now more robust, with code taken from Lutris/Proton.
- The troubleshooting log now includes the nvngx.dll detected path, for better troubleshooting in case of bugs. There's also a lot of logs about the detection if something goes wrong

**Pull request merged**
